In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np, os
import matplotlib.pyplot as plt

from pathlib import Path
# import yaml
# import re
# import datetime

# import pyarrow as pa
# import pyarrow.parquet as pq

# import gbd_mapping as gm
# from vivarium import Artifact

# from db_queries import get_ids, get_outputs, get_population, get_covariate_estimates
# from get_draws.api import get_draws

import vivarium_helpers as vh
# import vivarium_helpers.id_helper as idh
# from vivarium_helpers.vph_output.operations import VPHOperator
# from vivarium_helpers.vph_output.measures import VPHResults
from vivarium_helpers.utils import convert_to_categorical, constant_categorical, print_memory_usage, Timer
# from vivarium_helpers.vph_output import cleaning
# from vivarium_helpers.vph_output.loading import load_draws_from_keyspace_files
from vivarium_helpers.projects.alzheimers import loading, population
from vivarium_helpers.projects.alzheimers.population import RunType
# from vivarium_helpers.vph_artifact.operations import convert_to_sim_format
from vivarium_helpers.projects.alzheimers.results import AlzheimersResultsProcessor

!date
!whoami
!uname -a
!pwd

Sat Feb 21 00:48:46 PST 2026
ndbs
Linux long-slurm-sarchive-p0061 5.4.0-216-generic #236-Ubuntu SMP Fri Apr 11 19:53:21 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
/mnt/share/code/ndbs/vivarium_research_alzheimers/results_tables

In [3]:
# from vivarium_helpers.projects.alzheimers.results import AlzheimersResultsProcessor

# Record version of Vivarium Helpers

In [4]:
!conda list | grep vivarium

# packages in environment at /ihme/homes/ndbs/miniconda3/envs/vivarium_csu_alzheimers_artifact:
vivarium                  3.4.12                   pypi_0    pypi
vivarium-build-utils      2.0.4                    pypi_0    pypi
vivarium-cluster-tools    2.1.17                   pypi_0    pypi
vivarium-csu-alzheimers   0.1.dev18+g43e997c.d20250808          pypi_0    pypi
vivarium-dependencies     1.0.1                    pypi_0    pypi
vivarium-gbd-access       4.2.4                    pypi_0    pypi
vivarium-helpers          0.2.0                     dev_0    <develop>
vivarium-inputs           6.0.4                    pypi_0    pypi
vivarium-public-health    4.3.5                    pypi_0    pypi

In [5]:
!pip freeze | grep vivarium

vivarium==3.4.12
vivarium_build_utils==2.0.4
vivarium_cluster_tools==2.1.17
-e git+https://github.com/ihmeuw/vivarium_csu_alzheimers.git@263eb3d9b80b13735a7380bb892430eaba92603a#egg=vivarium_csu_alzheimers
vivarium_dependencies==1.0.1
vivarium_gbd_access==4.2.4
-e git+https://github.com/ihmeuw/vivarium_helpers.git@99e2ba7ca769ee1a206682a4f85cb224c9a930ff#egg=vivarium_helpers
vivarium_inputs==6.0.4
vivarium_public_health==4.3.5

# Define data directories

In [6]:
# Project directory
project_dir = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/')

# Output directory to store final results for client
output_dir = Path(r"J:\Project\simulation_science\alzheimers\results_in_progress".replace('\\', '/').replace('J:', '/snfs1'))
print(output_dir.exists())

# Output from multistate life table
# mslt_output_dir = output_dir.parent / 'results_12_4_2025_mslt'
mslt_output_dir = project_dir / 'results' / 'mslt_draws'
print(mslt_output_dir.exists())
output_dir

True

True

PosixPath('/snfs1/Project/simulation_science/alzheimers/results_in_progress')

In [7]:
# # For testing: Run directory containing model 8.3 results for all
# # locations
# model_run_subdir = 'results/abie_consistent_model_test/united_states_of_america/2025_10_28_08_55_05/'

# # Results directory for model 8.3, for testing
# results_dirs = project_dir / model_run_subdir / 'results/'

# Artifact for models 10.0 - 12.2
artifact_model_number = '10.0'

In [8]:
# Model 8.4 results (final runs for 10/31/25 intermediate results)
# Each batch run contains all locations, 100 random seeds, and 3 or 4 draws
model_run_dir_8_4 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model8.4/model_spec')

# Model 8.7 results (updated final run completed on 11/10/2025)
model_run_dir_8_7 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model8.7/model_spec')

# Model 12.2 results (updated final run completed on 02/14/2026)
model_run_dir_12_2 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2')

# Batch runs are stored in "timestamp" subdirectories of the model run
# directory.
# In model 12.2, the run directories are nested under two more levels of
# subfolders: batch number, then model_spec, then timestamp.

# Select a model and filter for testing
batch_run_dirs = loading.list_batch_run_directories(model_run_dir_12_2)#[:2]

# batch_results_dirs
batch_run_dirs

['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch3/model_spec/2026_02_13_17_10_34',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch2/model_spec/2026_02_13_15_02_52',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch10/model_spec/2026_02_14_06_55_09',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch6/model_spec/2026_02_13_18_33_24',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch7/model_spec/2026_02_13_21_04_24',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch4/model_spec/2026_02_13_17_14_14']

# Create an AlzheimersResultsProcessor object to process results

In [9]:
results = AlzheimersResultsProcessor('10.0', RunType.FINAL, batch_run_dirs=batch_run_dirs)

In [10]:
results.initial_simulation_population

2000000

In [11]:
results.locations

['United States of America',
 'Brazil',
 'China',
 'Germany',
 'Israel',
 'Japan',
 'Spain',
 'Sweden',
 'Taiwan (Province of China)',
 'United Kingdom']

In [12]:
results.draws

[35,
 187,
 41,
 123,
 248,
 122,
 183,
 103,
 161,
 50,
 24,
 172,
 235,
 245,
 69,
 204,
 219,
 63,
 199,
 6,
 249,
 7,
 236,
 1,
 211]

# Load population data and calculate model scale

In [13]:
with Timer():
    results.load_population_data(append_aggregates=True)
results.ops.describe(results.model_scale)

Elapsed time: 0:00:19.684869

,count,mean,std,min,25%,50%,75%,max
location,,,,,,,,
Brazil,25.0,0.645126,0.042517,0.544775,0.618288,0.636986,0.682593,0.718303
China,25.0,0.075453,0.003924,0.067459,0.072855,0.075736,0.077771,0.085044
Germany,25.0,0.548393,0.025209,0.498396,0.536829,0.546442,0.557773,0.604171
Israel,25.0,26.039578,2.496689,20.549962,24.481746,25.631266,28.245708,30.287894
Japan,25.0,0.354952,0.020849,0.308678,0.339599,0.355165,0.367604,0.399881
Spain,25.0,1.865326,0.083683,1.719458,1.822242,1.856133,1.887104,2.134511
Sweden,25.0,7.785869,0.522496,6.614222,7.413090,7.838525,8.131916,8.716418
Taiwan (Province of China),25.0,5.271920,0.276774,4.659120,5.108985,5.251648,5.484657,5.726114
United Kingdom,25.0,1.229875,0.047735,1.167644,1.185930,1.220243,1.267019,1.318293
United States of America,25.0,0.275399,0.015292,0.251900,0.264626,0.274222,0.284826,0.322825

In [14]:
results.person_time

,location,sex,event_year,input_draw,value,age_group
0,United States of America,Female,2025,35,1.097634e+07,65_to_69
1,United States of America,Female,2025,187,1.066321e+07,65_to_69
2,United States of America,Female,2025,41,1.063578e+07,65_to_69
3,United States of America,Female,2025,123,1.104572e+07,65_to_69
4,United States of America,Female,2025,248,1.080614e+07,65_to_69
...,...,...,...,...,...,...
911995,Spain,Both,2100,249,1.552865e+07,65_plus
911996,Sweden,Both,2100,249,3.047298e+06,65_plus
911997,Taiwan (Province of China),Both,2100,249,7.422109e+06,65_plus
911998,United Kingdom,Both,2100,249,1.859581e+07,65_plus
911999,United States of America,Both,2100,249,7.741236e+07,65_plus

In [15]:
results.person_time.input_draw.unique()

array([ 35, 187,  41, 123, 248, 122, 183, 103, 161,  50,  24, 172, 235,
       245,  69, 204, 219,  63, 199,   6, 249,   7, 236,   1, 211],
      dtype=int16)

In [16]:
results.person_time.age_group.unique()

['65_to_69', '70_to_74', '75_to_79', '80_to_84', '85_to_89', ..., '45_to_49', '50_to_54', '55_to_59', '60_to_64', '65_plus']
Length: 16
Categories (16, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '85_to_89' < '90_to_94' < '95_plus' < '65_plus']

# Load and process deaths data for testing

In [17]:
# with Timer():
#     results.load_measure_from_batch_runs('deaths', filters=loading.FINAL_RESULTS_FILTERS['deaths'])

In [18]:
# results.data.deaths

In [19]:
# deaths_prepped = results.process_deaths(results.data.deaths)
# deaths_prepped

# Preprocess MSLT results

In [20]:
!ls $mslt_output_dir

v4_2026_01_14_outside_sim_results_draw_level.csv
v4_2026_02_03_outside_sim_results_draw_level.csv
v4_2026_02_18_outside_sim_results_draw_level.csv

In [21]:
mslt_results = pd.read_csv(mslt_output_dir / 'v4_2026_02_18_outside_sim_results_draw_level.csv', index_col=0)
mslt_results

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Draw,Value
0,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_1,0.000000
1,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_103,0.000000
2,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_122,0.000000
3,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_123,0.000000
4,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_161,0.000000
...,...,...,...,...,...,...,...,...,...,...
113995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_50,2015.073423
113996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_6,1966.509895
113997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_63,2025.659827
113998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_69,2127.428568
113999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_7,2046.368615

In [22]:
mslt_results.Age.unique()

array(['65_to_69', '70_to_74', '75_to_79'], dtype=object)

In [23]:
mslt_results.Draw.unique()

array(['draw_1', 'draw_103', 'draw_122', 'draw_123', 'draw_161',
       'draw_172', 'draw_183', 'draw_187', 'draw_199', 'draw_204',
       'draw_211', 'draw_219', 'draw_235', 'draw_236', 'draw_24',
       'draw_245', 'draw_248', 'draw_249', 'draw_35', 'draw_41',
       'draw_50', 'draw_6', 'draw_63', 'draw_69', 'draw_7'], dtype=object)

In [24]:
mslt_results.Scenario.unique()

array(['BBBM Testing Only', 'BBBM Testing and Treatment'], dtype=object)

In [25]:
mslt_results_prepped = results.process_mslt_results(mslt_results)
mslt_results_prepped

,input_draw,location,age_group,disease_stage,event_year,measure,metric,scenario,sex,value
0,1,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
1,1,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
2,1,Brazil,75_to_79,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
3,1,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Male,0.000000
4,1,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Male,0.000000
...,...,...,...,...,...,...,...,...,...,...
683995,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,648.594446
683996,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,627.810266
683997,249,United States of America,65_to_69,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,786.064602
683998,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,592.328371
683999,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,573.347234

In [26]:
mslt_results_prepped.measure.unique()

['BBBM Tests', 'Positive BBBM Tests', 'Medication Initiation']
Categories (3, object): ['BBBM Tests', 'Medication Initiation', 'Positive BBBM Tests']

# BBBM Test Counts

In [27]:
filename = 'counts_bbbm_tests'
# short_name = 'bbbm_tests'
with Timer():
    bbbm_tests = results.load_measure_from_batch_runs(
        filename, False, filters=loading.FINAL_RESULTS_FILTERS[filename])

bbbm_tests

Timer BatchLoadingTimer started
[('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
186.059997 MB after read_parquet
1.209888 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}

,age_group,artifact_path,bbbm_test_results,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing,Female,,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing,Male,,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing_and_treatment,Female,,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing_and_treatment,Male,,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,187,counts_bbbm_tests,bbbm_testing,Female,,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
455995,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,1,counts_bbbm_tests,bbbm_testing_and_treatment,Male,,14465.0,Brazil
455996,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,211,counts_bbbm_tests,bbbm_testing,Female,,24094.0,Brazil
455997,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,211,counts_bbbm_tests,bbbm_testing,Male,,10437.0,Brazil
455998,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,211,counts_bbbm_tests,bbbm_testing_and_treatment,Female,,24094.0,Brazil
455999,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,211,counts_bbbm_tests,bbbm_testing_and_treatment,Male,,10437.0,Brazil

In [28]:
bbbm_tests.age_group.unique()

['65_to_69', '70_to_74', '75_to_79']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [29]:
bbbm_tests.query("value>0").age_group.unique()

['65_to_69', '70_to_74', '75_to_79']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [30]:
bbbm_tests.bbbm_test_results.unique()

['positive', 'negative']
Categories (3, object): ['negative', 'not_tested', 'positive']

In [31]:
bbbm_tests.query("value>0").scenario.unique()

['bbbm_testing', 'bbbm_testing_and_treatment']
Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [32]:
bbbm_tests_prepped = results.process_bbbm_tests(bbbm_tests, mslt_results_prepped)
bbbm_tests_prepped

,age_group,event_year,input_draw,location,measure,scenario,sex,value,disease_stage,metric
0,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
1,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Male,0.000000,Preclinical AD,Number
2,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Female,0.000000,Preclinical AD,Number
3,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Male,0.000000,Preclinical AD,Number
4,65_to_69,2025,6,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
...,...,...,...,...,...,...,...,...,...,...
911995,70_to_74,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Female,818.493948,Susceptible,Number
911996,75_to_79,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Female,792.265345,Susceptible,Number
911997,65_to_69,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,991.974449,Susceptible,Number
911998,70_to_74,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,747.488957,Susceptible,Number
911999,75_to_79,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,723.535706,Susceptible,Number

In [33]:
bbbm_tests_prepped.disease_stage.unique()

['Preclinical AD', 'Susceptible']
Categories (2, object): ['Preclinical AD', 'Susceptible']

In [34]:
bbbm_tests_prepped.measure.unique()

['BBBM Tests', 'Positive BBBM Tests']
Categories (2, object): ['BBBM Tests', 'Positive BBBM Tests']

In [35]:
with Timer():
    bbbm_tests_output = results.summarize_and_beautify(bbbm_tests_prepped, 'disease_stage')
bbbm_tests_output
# 121600 rows

Timer SummarizingTimer started
2026-02-21 00:49:46.825399
2026-02-21 00:49:55.492921
2026-02-21 00:52:50.048488
Elapsed time: 183.2318 seconds
Elapsed time: 0:03:03.232048

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
145915,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000250,0.000245,0.000253
145916,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000237,0.000233,0.000241
145917,2100,United States of America,65_plus,Female,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000226,0.000222,0.000232
145918,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000250,0.000245,0.000253
145919,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000237,0.000233,0.000241

In [36]:
bbbm_tests_output.Measure.unique()

['BBBM Tests', 'Positive BBBM Tests']
Categories (2, object): ['BBBM Tests', 'Positive BBBM Tests']

In [37]:
bbbm_tests_output.Age.unique()

['65_to_69', '70_to_74', '75_to_79', '65_plus']
Categories (4, object): ['65_plus', '65_to_69', '70_to_74', '75_to_79']

In [38]:
bbbm_tests_output.query("Mean>0").Scenario.unique()

['BBBM Testing Only', 'BBBM Testing and Treatment']
Categories (2, object): ['BBBM Testing Only', 'BBBM Testing and Treatment']

In [39]:
bbbm_tests_output.query(
    "Year == 2100 & Location == 'United States of America' & Age == '75_to_79' & Sex == 'Male' & `Disease Stage` == 'Susceptible' & Scenario == 'BBBM Testing Only' & Measure == 'Positive BBBM Tests'"
)

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
109429,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Number,2597.044405,2359.099291,2779.016486
109435,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000396,0.000391,0.000400

### Testing some stuff...

In [40]:
# temp = results.do_final_processing(bbbm_tests_prepped)
# temp

In [41]:
# results.ops.assert_values_equal(temp, bbbm_tests_output, value_cols=['Mean', '95% UI Lower', '95% UI Upper'], check_exact=False)

In [42]:
# temp2 = results.do_final_processing(bbbm_tests_prepped, include_draws=False)
# temp2

In [43]:
# results.ops.assert_values_equal(temp2, bbbm_tests_output, value_cols=['Mean', '95% UI Lower', '95% UI Upper'], check_exact=False)

In [44]:
# temp3 = results.do_final_processing(bbbm_tests_prepped, include_draws=True)
# temp3

In [46]:
# results.ops.assert_values_equal(
#     temp3.drop(columns=[c for c in temp3.columns if c.startswith('draw_')]),
#     bbbm_tests_output, value_cols=['Mean', '95% UI Lower', '95% UI Upper'], check_exact=False)

In [47]:
# Save BBBM testing results
bbbm_tests_output.to_csv(output_dir / 'bbbm_tests.csv', index=False)

# CSF and PET Test Counts

In [48]:
# csf_pet_filters = [('testing_state', 'in', ['csf', 'pet'])]
filename = 'counts_baseline_tests_among_eligible'
with Timer():
    csf_pet_tests = results.load_measure_from_batch_runs(
        filename, False, filters=loading.FINAL_RESULTS_FILTERS[filename]
    )
print(len(csf_pet_tests), 'rows')
csf_pet_tests.head()

Timer BatchLoadingTimer started
[('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
930.252135 MB after read_parquet
6.025386 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
930.252135 MB after read_parquet
6.025386 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
930.252135 MB after read_parquet
6.025386 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
930.252135 MB after read_parquet
6.025386 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
1395.372135 MB after read_parquet
9.034986 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,testing_state,value,location
0,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Female,,csf,0.0,Japan
1,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Female,,pet,0.0,Japan
2,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Male,,csf,0.0,Japan
3,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Male,,pet,0.0,Japan
4,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,bbbm_testing,Female,,csf,0.0,Japan

In [49]:
csf_pet_tests.query("value>0").age_group.unique()

['30_to_34', '35_to_39', '40_to_44', '45_to_49', '50_to_54', ..., '75_to_79', '80_to_84', '85_to_89', '90_to_94', '95_plus']
Length: 14
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [50]:
csf_pet_tests_prepped = results.process_csf_pet_tests(csf_pet_tests)
csf_pet_tests_prepped

102.606297 MB measure
34.206297 MB minuend
68.406297 MB subtrahend
22.810452 MB minuend re-indexed
45.610452 MB subtrahend re-indexed
45.610512 MB difference
77.526429 MB difference with reset index
79.806754 MB final difference

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,testing_state,value,location,metric,disease_stage
0,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,CSF Tests,baseline,Female,,csf,0.0,Japan,Number,MCI due to AD
1,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,PET Tests,baseline,Female,,pet,0.0,Japan,Number,MCI due to AD
2,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,CSF Tests,baseline,Male,,csf,0.0,Japan,Number,MCI due to AD
3,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,PET Tests,baseline,Male,,pet,0.0,Japan,Number,MCI due to AD
4,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,CSF Tests,bbbm_testing,Female,,csf,0.0,Japan,Number,MCI due to AD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5699995,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted PET Tests,bbbm_testing,Male,,pet,19.0,Brazil,Number,MCI due to AD
5699996,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted CSF Tests,bbbm_testing_and_treatment,Female,,csf,43.0,Brazil,Number,MCI due to AD
5699997,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted PET Tests,bbbm_testing_and_treatment,Female,,pet,68.0,Brazil,Number,MCI due to AD
5699998,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted CSF Tests,bbbm_testing_and_treatment,Male,,csf,14.0,Brazil,Number,MCI due to AD
5699999,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted PET Tests,bbbm_testing_and_treatment,Male,,pet,19.0,Brazil,Number,MCI due to AD

In [51]:
csf_pet_tests_output = results.summarize_and_beautify(csf_pet_tests_prepped, 'disease_stage')
csf_pet_tests_output

Timer SummarizingTimer started
2026-02-21 00:57:20.612419
2026-02-21 00:58:10.529887
2026-02-21 01:12:43.168493
Elapsed time: 922.5779 seconds

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_to_69,Female,MCI due to AD,Reference,CSF Tests,Number,3365.354044,1850.986316,4901.104480
1,2025,Brazil,65_to_69,Male,MCI due to AD,Reference,CSF Tests,Number,1320.010850,814.662530,2000.888203
2,2025,Brazil,65_to_69,Both,MCI due to AD,Reference,CSF Tests,Number,4685.364895,2693.215770,6694.730002
3,2025,Brazil,65_to_69,Female,MCI due to AD,BBBM Testing Only,CSF Tests,Number,3365.354044,1850.986316,4901.104480
4,2025,Brazil,65_to_69,Male,MCI due to AD,BBBM Testing Only,CSF Tests,Number,1320.010850,814.662530,2000.888203
...,...,...,...,...,...,...,...,...,...,...,...
729595,2100,United States of America,65_plus,Male,MCI due to AD,BBBM Testing Only,Averted PET Tests,Rate,0.000418,0.000187,0.000596
729596,2100,United States of America,65_plus,Both,MCI due to AD,BBBM Testing Only,Averted PET Tests,Rate,0.000558,0.000269,0.000766
729597,2100,United States of America,65_plus,Female,MCI due to AD,BBBM Testing and Treatment,Averted PET Tests,Rate,0.000673,0.000338,0.000906
729598,2100,United States of America,65_plus,Male,MCI due to AD,BBBM Testing and Treatment,Averted PET Tests,Rate,0.000418,0.000187,0.000596
729599,2100,United States of America,65_plus,Both,MCI due to AD,BBBM Testing and Treatment,Averted PET Tests,Rate,0.000558,0.000269,0.000766

In [52]:
# Save CSF/PET testing results
csf_pet_tests_output.to_csv(output_dir / 'csf_pet_tests.csv', index=False)

# Treatment Counts

We count treatments using treatment transition counts in older models, and with the treatment duration counts starting in model 11.0

In [53]:
# treatments_filters = [
#     ('sub_entity', 'in',
#      ['susceptible_to_treatment_to_waiting_for_treatment',
#       'waiting_for_treatment_to_full_effect_long',
#       'waiting_for_treatment_to_full_effect_short']
#     )
# ]
treatment_transitions_filename = 'transition_count_treatment'

with Timer():
    treatment_transitions = results.load_measure_from_batch_runs(
        treatment_transitions_filename, False, 
        filters=loading.FINAL_RESULTS_FILTERS[treatment_transitions_filename]
    )
print(len(treatment_transitions), 'rows')
treatment_transitions.head()

Timer BatchLoadingTimer started
[('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84']), ('scenario', '==', 'bbbm_testing_and_treatment')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84']), ('scenario', '==', 'bbbm_testing_and_treatment')]
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84']), ('scenario', '==', 'bbbm_testing_and_treatment')]
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84']), ('scenario', '==', 'bbbm_testing_and_treatment')]
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84']), ('scenario', '==', 'bbbm_testing_and_treatment')]
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84']), ('scenario', '==', 'bbbm_testing_and_treatment')]
60.204194 MB after read_parquet
0.389285 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,transition_count,bbbm_testing_and_treatment,Female,waiting_for_treatment_to_treatment_effect,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,transition_count,bbbm_testing_and_treatment,Male,waiting_for_treatment_to_treatment_effect,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,187,transition_count,bbbm_testing_and_treatment,Female,waiting_for_treatment_to_treatment_effect,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,187,transition_count,bbbm_testing_and_treatment,Male,waiting_for_treatment_to_treatment_effect,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2026,35,transition_count,bbbm_testing_and_treatment,Female,waiting_for_treatment_to_treatment_effect,0.0,Japan

In [54]:
treatment_transitions.sub_entity.unique()

['waiting_for_treatment_to_treatment_effect']
Categories (5, object): ['susceptible_to_treatment_to_no_effect_never_t..., 'susceptible_to_treatment_to_waiting_for_treat..., 'treatment_effect_to_waning_effect', 'waiting_for_treatment_to_treatment_effect', 'waning_effect_to_no_effect_after_treatment']

In [55]:
treatment_transitions.query("value>0").scenario.unique()

['bbbm_testing_and_treatment']
Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [56]:
treatment_months_filename = 'treatment_duration'
# treatment_months_filters = [
#     ('sub_entity', '!=', 0),
#     ('age_group', 'in', loading.TESTING_ELIGIBLE_AGE_GROUPS),
#     # ('scenario', '==', 'bbbm_testing_and_treatment'),
# ] 

with Timer():
    treatment_months = results.load_measure_from_batch_runs(
        treatment_months_filename, False,
        filters=loading.FINAL_RESULTS_FILTERS[treatment_months_filename]
    )
print(len(treatment_months), 'rows')
treatment_months.head()

Timer BatchLoadingTimer started
[('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
492.491529 MB after read_parquet
2.591472 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan

In [57]:
treatment_months.query("value>0").sub_entity.unique()

[1, 6, 9, 7, 3, 4, 8, 2, 5]
Categories (9, int64): [1, 2, 3, 4, ..., 6, 7, 8, 9]

In [58]:
treatment_months.query("value>0").scenario.unique()

['bbbm_testing_and_treatment']
Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [59]:
start_treatment = [
        'waiting_for_treatment_to_full_effect_long',
        'waiting_for_treatment_to_full_effect_short',
        'waiting_for_treatment_to_treatment_effect']
treatment_transitions.query("sub_entity in @start_treatment and value>0").age_group.unique()

['65_to_69', '70_to_74', '75_to_79', '80_to_84']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [60]:
# # Now empty because we filter out this transition on loading
# treatments.query("sub_entity=='susceptible_to_treatment_to_waiting_for_treatment' and value>0").age_group.unique()
# # Should be ['60_to_64', '65_to_69', '70_to_74', '75_to_79']

In [61]:
# Check which transitions are present in the treatment transitions
# dataframe, to determine whether we should use treatment transition
# counts or treatment duration counts to count completed vs.
# discontinued treatments
unique_transitions = treatment_transitions['sub_entity'].unique()

if ('waiting_for_treatment_to_full_effect_long' in unique_transitions
    and 'waiting_for_treatment_to_full_effect_short' in unique_transitions):
    treatments = treatment_transitions
elif 'waiting_for_treatment_to_treatment_effect' in unique_transitions:
    treatments = treatment_months
else:
    raise ValueError(
        f"Missing expected treatment transitions: {unique_transitions}")

treatments

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...
1025995,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,5,117.0,Brazil
1025996,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,6,95.0,Brazil
1025997,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,7,101.0,Brazil
1025998,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,8,109.0,Brazil
1025999,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,9,7602.0,Brazil

In [62]:
treatments_prepped = results.process_treatments(treatments, mslt_results_prepped)
treatments_prepped

,age_group,event_year,input_draw,location,scenario,sex,measure,value,disease_stage
0,65_to_69,2025,1,Japan,bbbm_testing_and_treatment,Female,Medication Discontinuation,0.000000,Preclinical AD
1,65_to_69,2025,1,Japan,bbbm_testing_and_treatment,Female,Medication Completion,0.000000,Preclinical AD
2,65_to_69,2025,1,Japan,bbbm_testing_and_treatment,Male,Medication Discontinuation,0.000000,Preclinical AD
3,65_to_69,2025,1,Japan,bbbm_testing_and_treatment,Male,Medication Completion,0.000000,Preclinical AD
4,65_to_69,2025,6,Japan,bbbm_testing_and_treatment,Female,Medication Discontinuation,0.000000,Preclinical AD
...,...,...,...,...,...,...,...,...,...
455995,70_to_74,2100,249,United States of America,BBBM Testing and Treatment,Female,Medication Initiation,648.594446,Susceptible
455996,75_to_79,2100,249,United States of America,BBBM Testing and Treatment,Female,Medication Initiation,627.810266,Susceptible
455997,65_to_69,2100,249,United States of America,BBBM Testing and Treatment,Male,Medication Initiation,786.064602,Susceptible
455998,70_to_74,2100,249,United States of America,BBBM Testing and Treatment,Male,Medication Initiation,592.328371,Susceptible
455999,75_to_79,2100,249,United States of America,BBBM Testing and Treatment,Male,Medication Initiation,573.347234,Susceptible

In [63]:
treatments_prepped.query("measure=='Medication Initiation'").disease_stage.unique()

['Preclinical AD', 'Susceptible']
Categories (2, object): ['Preclinical AD', 'Susceptible']

In [64]:
treatments_prepped.query("disease_stage=='Susceptible'").scenario.unique()

['BBBM Testing and Treatment']
Categories (2, object): ['BBBM Testing and Treatment', 'bbbm_testing_and_treatment']

In [65]:
treatments_prepped.query("scenario in ['BBBM Testing Only', 'bbbm_testing']").value.unique()

array([], dtype=float64)

In [66]:
with Timer():
    treatments_output = results.summarize_and_beautify(treatments_prepped, 'disease_stage')

print(len(treatments_output), 'rows')
treatments_output.head()

Timer SummarizingTimer started
2026-02-21 01:14:09.389391
2026-02-21 01:14:14.254961
2026-02-21 01:15:42.497914
Elapsed time: 93.1142 seconds
Elapsed time: 0:01:33.114432
72960 rows

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.0,0.0,0.0
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.0,0.0,0.0
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.0,0.0,0.0
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.0,0.0,0.0
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.0,0.0,0.0

In [67]:
treatments_output.query(
    "Year == 2100 & Location == 'United States of America' & Age == '75_to_79' & Sex == 'Male' & `Disease Stage` == 'Susceptible' & Scenario == 'BBBM Testing and Treatment' & Measure == 'Medication Initiation'"
)
# orig mean: 93092.973924
# new mean: 41049.447242

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
54715,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,2057.960945,1869.407469,2202.160034
54718,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Rate,0.000314,0.000310,0.000317

In [68]:
41049.447242 / 93092.973924

0.4409510783865631

In [98]:
treatments_output.isna().any().any()

False

In [69]:
# Save treatments output
treatments_output.to_csv(output_dir / 'medication.csv', index=False)

# Process months of treatment

In [70]:
treatment_months
# Needed columns:
# year, location, age group, sex, scenario, sub-entity (months of treatment), value (count)

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...
1025995,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,5,117.0,Brazil
1025996,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,6,95.0,Brazil
1025997,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,7,101.0,Brazil
1025998,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,8,109.0,Brazil
1025999,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,9,7602.0,Brazil

In [71]:
treatment_months_prepped = results.process_months_of_treatment(treatment_months)
treatment_months_prepped

,age_group,event_year,input_draw,measure,scenario,sex,doses_completed,value,location,metric,disease_stage
0,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,1,0,Japan,Number,Preclinical AD
1,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,2,0,Japan,Number,Preclinical AD
2,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,3,0,Japan,Number,Preclinical AD
3,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,4,0,Japan,Number,Preclinical AD
4,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,5,0,Japan,Number,Preclinical AD
...,...,...,...,...,...,...,...,...,...,...,...
1025995,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,5,117,Brazil,Number,Preclinical AD
1025996,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,6,95,Brazil,Number,Preclinical AD
1025997,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,7,101,Brazil,Number,Preclinical AD
1025998,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,8,109,Brazil,Number,Preclinical AD
1025999,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,9,7602,Brazil,Number,Preclinical AD

In [72]:
treatment_months_output = results.do_final_processing(treatment_months_prepped, include_draws=True)
treatment_months_output

2026-02-21 01:15:46.114621
Timer SummarizingTimer started
Elapsed time: 197.5916 seconds
2026-02-21 01:19:12.777355

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Doses Completed,Mean,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164155,2100,United States of America,65_plus,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,9,49719.422008,...,54454.245433,56943.517821,54084.857551,46983.824892,53108.150817,47446.992696,48813.107239,56001.113960,46599.328480,44567.922289
164156,2100,United States of America,65_plus,Both,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,9,139912.504418,...,149433.635072,154478.700673,157518.574777,139863.328269,144371.637040,141936.196273,136776.219435,147093.086609,142728.947015,137675.165883
164157,2100,United States of America,65_plus,Female,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,9,0.002109,...,0.002180,0.002241,0.002221,0.002174,0.002225,0.002189,0.002224,0.002146,0.002256,0.002200
164158,2100,United States of America,65_plus,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,9,0.001405,...,0.001516,0.001548,0.001420,0.001349,0.001549,0.001327,0.001498,0.001596,0.001306,0.001270
164159,2100,United States of America,65_plus,Both,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,9,0.001790,...,0.001880,0.001923,0.001861,0.001803,0.001917,0.001799,0.001896,0.001897,0.001823,0.001778

In [99]:
treatment_months_output.isna().any().any()

False

In [ ]:
# Save months of treatment output
# 41M when including 4 draws, 106M with 25 draws
treatment_months_output.to_csv(output_dir / 'medication_doses.csv', index=False)

# Check some stuff

In [74]:
!ls -halt $output_dir

total 581M
-rw-rw-r-- 1 ndbs       Domain Users 106M Feb 21 01:19 medication_doses.csv
-rw-rw-r-- 1 ndbs       Domain Users  12M Feb 21 01:15 medication.csv
drwxrwxr-x 6 ndbs       Domain Users    2 Feb 21 01:15 .
-rw-rw-r-- 1 ndbs       Domain Users  91M Feb 21 01:12 csf_pet_tests.csv
-rw-rw-r-- 1 ndbs       Domain Users  21M Feb 21 00:55 bbbm_tests.csv
-rw-rw-r-- 1 ndbs       Domain Users  84M Feb 17 18:18 prevalence.csv
-rw-rw-r-- 1 ndbs       Domain Users  48M Feb 17 18:06 deaths.csv
-rw-rw-r-- 1 ndbs       Domain Users  83M Feb 17 17:17 incidence.csv
-rw-rw-r-- 1 ndbs       Domain Users 139M Feb 17 17:05 dalys.csv
drwxrwxr-x 2 ndbs       Domain Users    0 Feb 17 14:47 version4
drwxrwxr-x 2 ndbs       Domain Users    0 Dec  5 01:17 version3
drwxrwxrwx 7 2074479877    310492440    0 Dec  4 13:19 ..
drwxrwxr-x 2 ndbs       Domain Users    0 Nov 24 20:19 version2
drwxrwxr-x 2 ndbs       Domain Users    0 Nov 17 11:53 version1

In [75]:
treatments_output

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
72955,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,7005.536753,6363.678942,7496.407105
72956,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,14679.795450,13353.887512,15662.160670
72957,2100,United States of America,65_plus,Female,Susceptible,BBBM Testing and Treatment,Medication Initiation,Rate,0.000179,0.000176,0.000183
72958,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Rate,0.000198,0.000194,0.000200
72959,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing and Treatment,Medication Initiation,Rate,0.000188,0.000185,0.000191

In [76]:
treatments_output.query("`Disease Stage` == 'Preclinical AD'").Year.unique()

[2025, 2026, 2027, 2028, 2029, ..., 2096, 2097, 2098, 2099, 2100]
Length: 76
Categories (76, int64): [2025, 2026, 2027, 2028, ..., 2097, 2098, 2099, 2100]

In [77]:
treatments_prepped.age_group.unique()

['65_to_69', '70_to_74', '75_to_79']
Categories (3, object): ['65_to_69', '70_to_74', '75_to_79']

In [78]:
treatment_rates = results.calculate_rate(treatments_prepped)
treatment_rates

,age_group,event_year,input_draw,location,sex,disease_stage,measure,scenario,value,metric
0,65_to_69,2025,1,Brazil,Both,NaN,NaN,NaN,NaN,Rate
1,65_to_69,2025,1,Brazil,Female,Preclinical AD,Medication Discontinuation,bbbm_testing_and_treatment,0.000000,Rate
2,65_to_69,2025,1,Brazil,Female,Preclinical AD,Medication Completion,bbbm_testing_and_treatment,0.000000,Rate
3,65_to_69,2025,1,Brazil,Female,Preclinical AD,Medication Initiation,bbbm_testing_and_treatment,0.000000,Rate
4,65_to_69,2025,1,Brazil,Female,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000000,Rate
...,...,...,...,...,...,...,...,...,...,...
512995,75_to_79,2100,249,United States of America,Female,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000083,Rate
512996,75_to_79,2100,249,United States of America,Male,Preclinical AD,Medication Discontinuation,bbbm_testing_and_treatment,0.000086,Rate
512997,75_to_79,2100,249,United States of America,Male,Preclinical AD,Medication Completion,bbbm_testing_and_treatment,0.000824,Rate
512998,75_to_79,2100,249,United States of America,Male,Preclinical AD,Medication Initiation,bbbm_testing_and_treatment,0.000910,Rate
512999,75_to_79,2100,249,United States of America,Male,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000089,Rate

In [79]:
treatment_rates.query("disease_stage=='Susceptible'")

,age_group,event_year,input_draw,location,sex,disease_stage,measure,scenario,value,metric
4,65_to_69,2025,1,Brazil,Female,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000000,Rate
8,65_to_69,2025,1,Brazil,Male,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000000,Rate
13,65_to_69,2025,1,China,Female,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000000,Rate
17,65_to_69,2025,1,China,Male,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000000,Rate
22,65_to_69,2025,1,Germany,Female,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000000,Rate
...,...,...,...,...,...,...,...,...,...,...
512981,75_to_79,2100,249,Taiwan (Province of China),Male,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.001557,Rate
512986,75_to_79,2100,249,United Kingdom,Female,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000325,Rate
512990,75_to_79,2100,249,United Kingdom,Male,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000334,Rate
512995,75_to_79,2100,249,United States of America,Female,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000083,Rate
512999,75_to_79,2100,249,United States of America,Male,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000089,Rate

In [80]:
mslt_results_prepped.query("measure.str.contains('Medication')")

,input_draw,location,age_group,disease_stage,event_year,measure,metric,scenario,sex,value
912,1,Brazil,65_to_69,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Female,0.000000
913,1,Brazil,70_to_74,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Female,0.000000
914,1,Brazil,75_to_79,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Female,0.000000
915,1,Brazil,65_to_69,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Male,0.000000
916,1,Brazil,70_to_74,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Male,0.000000
...,...,...,...,...,...,...,...,...,...,...
683995,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,648.594446
683996,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,627.810266
683997,249,United States of America,65_to_69,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,786.064602
683998,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,592.328371
683999,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,573.347234

In [81]:
mslt_results_prepped.measure.unique()

['BBBM Tests', 'Positive BBBM Tests', 'Medication Initiation']
Categories (3, object): ['BBBM Tests', 'Medication Initiation', 'Positive BBBM Tests']

# Scratchwork

In [82]:
bbbm_tests_prepped

,age_group,event_year,input_draw,location,measure,scenario,sex,value,disease_stage,metric
0,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
1,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Male,0.000000,Preclinical AD,Number
2,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Female,0.000000,Preclinical AD,Number
3,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Male,0.000000,Preclinical AD,Number
4,65_to_69,2025,6,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
...,...,...,...,...,...,...,...,...,...,...
911995,70_to_74,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Female,818.493948,Susceptible,Number
911996,75_to_79,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Female,792.265345,Susceptible,Number
911997,65_to_69,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,991.974449,Susceptible,Number
911998,70_to_74,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,747.488957,Susceptible,Number
911999,75_to_79,2100,249,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,723.535706,Susceptible,Number

In [83]:
column_name_map = {
            'event_year': 'Year',
            'age_group': 'Age',
            'location': 'Location',
            'sex': 'Sex',
            'scenario': 'Scenario',
            'measure': 'Measure',
            'metric': 'Metric',
            'disease_stage': 'Disease Stage',
            'input_draw': 'Draw',
            'value': 'Value',
            'mean': 'Mean',
            'lower': '95% UI Lower',
            'upper': '95% UI Upper',
        }
reverse_map = {v: k for k, v in column_name_map.items()}
reverse_map

{'Year': 'event_year',
 'Age': 'age_group',
 'Location': 'location',
 'Sex': 'sex',
 'Scenario': 'scenario',
 'Measure': 'measure',
 'Metric': 'metric',
 'Disease Stage': 'disease_stage',
 'Draw': 'input_draw',
 'Value': 'value',
 'Mean': 'mean',
 '95% UI Lower': 'lower',
 '95% UI Upper': 'upper'}

In [84]:
temp = mslt_results.rename(columns=reverse_map)
temp

,event_year,location,age_group,sex,disease_stage,scenario,measure,metric,input_draw,value
0,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_1,0.000000
1,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_103,0.000000
2,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_122,0.000000
3,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_123,0.000000
4,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_161,0.000000
...,...,...,...,...,...,...,...,...,...,...
113995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_50,2015.073423
113996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_6,1966.509895
113997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_63,2025.659827
113998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_69,2127.428568
113999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_7,2046.368615

In [85]:
pd.concat([bbbm_tests_prepped, temp])

,age_group,event_year,input_draw,location,measure,scenario,sex,value,disease_stage,metric
0,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
1,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Male,0.000000,Preclinical AD,Number
2,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Female,0.000000,Preclinical AD,Number
3,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Male,0.000000,Preclinical AD,Number
4,65_to_69,2025,6,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
...,...,...,...,...,...,...,...,...,...,...
113995,75_to_79,2100,draw_50,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,2015.073423,Susceptible,Number
113996,75_to_79,2100,draw_6,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,1966.509895,Susceptible,Number
113997,75_to_79,2100,draw_63,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,2025.659827,Susceptible,Number
113998,75_to_79,2100,draw_69,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,2127.428568,Susceptible,Number
113999,75_to_79,2100,draw_7,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,2046.368615,Susceptible,Number

In [86]:
temp.query("measure.str.contains('Medication') and value > 0 and scenario=='BBBM Testing Only'")

,event_year,location,age_group,sex,disease_stage,scenario,measure,metric,input_draw,value
1500,2035,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_1,316.746938
1501,2035,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_103,320.638000
1502,2035,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_122,291.644541
1503,2035,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_123,298.691131
1504,2035,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_161,278.956403
...,...,...,...,...,...,...,...,...,...,...
113995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_50,2015.073423
113996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_6,1966.509895
113997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_63,2025.659827
113998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_69,2127.428568
113999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_7,2046.368615

In [87]:
temp.measure.unique()

array(['BBBM Tests', 'BBBM False Positive Tests',
       'Improper Medication Uses'], dtype=object)

In [88]:
temp.replace(
    {'measure': {'BBBM False Positive Tests': 'BBBM Positive Tests',
 'Improper Medication Uses': 'Medication Initiation'}})

,event_year,location,age_group,sex,disease_stage,scenario,measure,metric,input_draw,value
0,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_1,0.000000
1,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_103,0.000000
2,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_122,0.000000
3,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_123,0.000000
4,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_161,0.000000
...,...,...,...,...,...,...,...,...,...,...
113995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_50,2015.073423
113996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_6,1966.509895
113997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_63,2025.659827
113998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_69,2127.428568
113999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_7,2046.368615

In [89]:
bbbm_tests_prepped.dtypes

age_group        category
event_year       category
input_draw       category
location         category
measure          category
scenario         category
sex              category
value             float64
disease_stage    category
metric           category
dtype: object

In [90]:
testing = temp.query("scenario=='BBBM Testing Only'").drop(columns='scenario')
treatment = temp.query("scenario=='BBBM Testing and Treatment'").drop(columns='scenario')
# This shows that the whole dataframe was copied to the testing-only
# scenario, including medication initiations, which is incorrect
results.ops.compare_values(testing, treatment)

Empty DataFrame
Columns: []
Index: []

In [91]:
mslt_results_processed = results.process_mslt_results(mslt_results)
mslt_results_processed

,input_draw,location,age_group,disease_stage,event_year,measure,metric,scenario,sex,value
0,1,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
1,1,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
2,1,Brazil,75_to_79,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
3,1,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Male,0.000000
4,1,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Male,0.000000
...,...,...,...,...,...,...,...,...,...,...
683995,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,648.594446
683996,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,627.810266
683997,249,United States of America,65_to_69,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,786.064602
683998,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,592.328371
683999,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,573.347234

In [92]:
mslt_results_processed.input_draw.unique()

[1, 6, 7, 24, 35, ..., 235, 236, 245, 248, 249]
Length: 25
Categories (25, int64): [1, 6, 7, 24, ..., 236, 245, 248, 249]

In [93]:
print_memory_usage(mslt_results_processed)

11.63405 MB

In [94]:
mslt_results_processed.measure.unique()

['BBBM Tests', 'Positive BBBM Tests', 'Medication Initiation']
Categories (3, object): ['BBBM Tests', 'Medication Initiation', 'Positive BBBM Tests']

In [95]:
!date

Sat Feb 21 01:19:29 PST 2026