In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np, os
import matplotlib.pyplot as plt

from pathlib import Path
# import yaml
# import re
# import datetime

# import pyarrow as pa
# import pyarrow.parquet as pq

# import gbd_mapping as gm
# from vivarium import Artifact

# from db_queries import get_ids, get_outputs, get_population, get_covariate_estimates
# from get_draws.api import get_draws

import vivarium_helpers as vh
# import vivarium_helpers.id_helper as idh
# from vivarium_helpers.vph_output.operations import VPHOperator
# from vivarium_helpers.vph_output.measures import VPHResults
from vivarium_helpers.utils import convert_to_categorical, constant_categorical, print_memory_usage, Timer
# from vivarium_helpers.vph_output import cleaning
# from vivarium_helpers.vph_output.loading import load_draws_from_keyspace_files
from vivarium_helpers.projects.alzheimers import loading, population
from vivarium_helpers.projects.alzheimers.population import RunType
# from vivarium_helpers.vph_artifact.operations import convert_to_sim_format
from vivarium_helpers.projects.alzheimers.results import AlzheimersResultsProcessor

!date
!whoami
!uname -a
!pwd

Mon 09 Mar 2026 05:25:21 PM PDT
ndbs
Linux int-slurm-sarchive-p0005 5.4.0-216-generic #236-Ubuntu SMP Fri Apr 11 19:53:21 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
/mnt/share/code/ndbs/vivarium_research_alzheimers/results_tables

In [3]:
# from vivarium_helpers.projects.alzheimers.results import AlzheimersResultsProcessor

# Record version of Vivarium Helpers

In [4]:
!conda list | grep vivarium

# packages in environment at /ihme/homes/ndbs/miniconda3/envs/vivarium_csu_alzheimers_artifact:
vivarium                  3.4.12                   pypi_0    pypi
vivarium-build-utils      2.0.4                    pypi_0    pypi
vivarium-cluster-tools    2.1.17                   pypi_0    pypi
vivarium-csu-alzheimers   0.1.dev18+g43e997c.d20250808          pypi_0    pypi
vivarium-dependencies     1.0.1                    pypi_0    pypi
vivarium-gbd-access       4.2.4                    pypi_0    pypi
vivarium-helpers          0.2.0                     dev_0    <develop>
vivarium-inputs           6.0.4                    pypi_0    pypi
vivarium-public-health    4.3.5                    pypi_0    pypi

In [5]:
!pip freeze | grep vivarium

vivarium==3.4.12
vivarium_build_utils==2.0.4
vivarium_cluster_tools==2.1.17
-e git+https://github.com/ihmeuw/vivarium_csu_alzheimers.git@263eb3d9b80b13735a7380bb892430eaba92603a#egg=vivarium_csu_alzheimers
vivarium_dependencies==1.0.1
vivarium_gbd_access==4.2.4
-e git+https://github.com/ihmeuw/vivarium_helpers.git@3efc22ea61849a210c7143d097900a2849e355ba#egg=vivarium_helpers
vivarium_inputs==6.0.4
vivarium_public_health==4.3.5

# Define data directories

In [6]:
# Project directory
project_dir = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/')

# Output directory to store final results for client
output_dir = Path(r"J:\Project\simulation_science\alzheimers\results_in_progress".replace('\\', '/').replace('J:', '/snfs1'))
print(output_dir.exists())

# Output from multistate life table
# mslt_output_dir = output_dir.parent / 'results_12_4_2025_mslt'
mslt_output_dir = project_dir / 'results' / 'mslt_draws'
print(mslt_output_dir.exists())
output_dir

True
True

PosixPath('/snfs1/Project/simulation_science/alzheimers/results_in_progress')

In [7]:
# # For testing: Run directory containing model 8.3 results for all
# # locations
# model_run_subdir = 'results/abie_consistent_model_test/united_states_of_america/2025_10_28_08_55_05/'

# # Results directory for model 8.3, for testing
# results_dirs = project_dir / model_run_subdir / 'results/'

# Artifact for models 10.0 - 12.2
artifact_model_number = '10.0'

In [8]:
# Model 8.4 results (final runs for 10/31/25 intermediate results)
# Each batch run contains all locations, 100 random seeds, and 3 or 4 draws
model_run_dir_8_4 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model8.4/model_spec')

# Model 8.7 results (updated final run completed on 11/10/2025)
model_run_dir_8_7 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model8.7/model_spec')

# Model 12.2 results (updated final run completed on 02/14/2026)
model_run_dir_12_2 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2')

# Batch runs are stored in "timestamp" subdirectories of the model run
# directory.
# In model 12.2, the run directories are nested under two more levels of
# subfolders: batch number, then model_spec, then timestamp.

# Select a model and filter for testing
batch_run_dirs = loading.list_batch_run_directories(model_run_dir_12_2)#[:2]

# batch_results_dirs
batch_run_dirs

['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch3/model_spec/2026_02_13_17_10_34',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch2/model_spec/2026_02_13_15_02_52',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch10/model_spec/2026_02_14_06_55_09',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch6/model_spec/2026_02_13_18_33_24',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch7/model_spec/2026_02_13_21_04_24',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch4/model_spec/2026_02_13_17_14_14']

# Create an AlzheimersResultsProcessor object to process results

In [9]:
results = AlzheimersResultsProcessor('10.0', RunType.FINAL, batch_run_dirs=batch_run_dirs)

In [10]:
results.initial_simulation_population

2000000

In [11]:
results.locations

['United States of America',
 'Brazil',
 'China',
 'Germany',
 'Israel',
 'Japan',
 'Spain',
 'Sweden',
 'Taiwan (Province of China)',
 'United Kingdom']

In [12]:
results.draws

[35,
 187,
 41,
 123,
 248,
 122,
 183,
 103,
 161,
 50,
 24,
 172,
 235,
 245,
 69,
 204,
 219,
 63,
 199,
 6,
 249,
 7,
 236,
 1,
 211]

# Load population data and calculate model scale

In [13]:
with Timer():
    results.load_population_data(append_aggregates=False)
results.ops.describe(results.model_scale)

Elapsed time: 0:00:14.928439

,count,mean,std,min,25%,50%,75%,max
location,,,,,,,,
Brazil,25.0,0.645126,0.042517,0.544775,0.618288,0.636986,0.682593,0.718303
China,25.0,0.075453,0.003924,0.067459,0.072855,0.075736,0.077771,0.085044
Germany,25.0,0.548393,0.025209,0.498396,0.536829,0.546442,0.557773,0.604171
Israel,25.0,26.039578,2.496689,20.549962,24.481746,25.631266,28.245708,30.287894
Japan,25.0,0.354952,0.020849,0.308678,0.339599,0.355165,0.367604,0.399881
Spain,25.0,1.865326,0.083683,1.719458,1.822242,1.856133,1.887104,2.134511
Sweden,25.0,7.785869,0.522496,6.614222,7.413090,7.838525,8.131916,8.716418
Taiwan (Province of China),25.0,5.271920,0.276774,4.659120,5.108985,5.251648,5.484657,5.726114
United Kingdom,25.0,1.229875,0.047735,1.167644,1.185930,1.220243,1.267019,1.318293
United States of America,25.0,0.275399,0.015292,0.251900,0.264626,0.274222,0.284826,0.322825

In [14]:
results.person_time

,location,sex,event_year,input_draw,value,age_group
0,United States of America,Female,2025,35,1.164474e+07,25_to_29
1,United States of America,Female,2025,187,1.125975e+07,25_to_29
2,United States of America,Female,2025,41,1.126842e+07,25_to_29
3,United States of America,Female,2025,123,1.171134e+07,25_to_29
4,United States of America,Female,2025,248,1.149482e+07,25_to_29
...,...,...,...,...,...,...
569995,United Kingdom,Male,2100,249,1.432651e+05,95_plus
569996,United Kingdom,Male,2100,7,1.488699e+05,95_plus
569997,United Kingdom,Male,2100,236,1.018623e+05,95_plus
569998,United Kingdom,Male,2100,1,1.332201e+05,95_plus
569999,United Kingdom,Male,2100,211,1.360060e+05,95_plus

In [15]:
results.person_time.input_draw.unique()

array([ 35, 187,  41, 123, 248, 122, 183, 103, 161,  50,  24, 172, 235,
       245,  69, 204, 219,  63, 199,   6, 249,   7, 236,   1, 211],
      dtype=int16)

In [16]:
results.person_time.age_group.unique()

['25_to_29', '30_to_34', '35_to_39', '40_to_44', '45_to_49', ..., '75_to_79', '80_to_84', '85_to_89', '90_to_94', '95_plus']
Length: 15
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

# Load prevalence and append counterfactual person-time

This calculates counterfactual person-time in treatment scenario for correct rate calculations.

In [17]:
with Timer():
    results.load_prevalence_and_append_counterfactual_person_time(append_aggregates=True)
results.person_time

Timer BatchLoadingTimer started
[('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
1896.059928 MB after read_parquet
12.071739 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch3/model_spec/2026_02_13_17_10_34/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch2/model_spec/2026_02_13_15_02_52/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch10/model_spec/2026_02_14_06_55_09/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch6/model_spec/2026_02_13_18_33_24/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch7/model_spec/2026_02_13_21_04_24/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch4/model_spec/2026_02_13_17_14_14/results')}
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
100.553979 MB total
100.553979 MB after enforcing dtypes
Elapsed time: 129.7994 seconds
95.769617 MB measure
89.385485 MB minuend
44.697485 MB subtrahend
63.850265 MB minuend re-indexed
31.930265 MB subtrahend re-indexed
63.850325 MB difference
63.849617 MB difference with reset index
67.041942 MB final difference
Elapsed time: 0:02:22.483920

,location,sex,event_year,input_draw,value,age_group,scenario
0,United States of America,Female,2025,35,1.097634e+07,65_to_69,baseline
1,United States of America,Female,2025,187,1.066321e+07,65_to_69,baseline
2,United States of America,Female,2025,41,1.063578e+07,65_to_69,baseline
3,United States of America,Female,2025,123,1.104572e+07,65_to_69,baseline
4,United States of America,Female,2025,248,1.080614e+07,65_to_69,baseline
...,...,...,...,...,...,...,...
2621995,United Kingdom,Both,2100,249,4.067978e+05,95_plus,bbbm_testing
2621996,United Kingdom,Both,2100,249,4.094528e+05,95_plus,bbbm_testing_and_treatment
2621997,United States of America,Both,2100,249,1.977824e+06,95_plus,baseline
2621998,United States of America,Both,2100,249,1.977824e+06,95_plus,bbbm_testing
2621999,United States of America,Both,2100,249,1.987725e+06,95_plus,bbbm_testing_and_treatment

# Load and process deaths data for testing

In [18]:
# with Timer():
#     results.load_measure_from_batch_runs('deaths', filters=loading.FINAL_RESULTS_FILTERS['deaths'])

In [19]:
# results.data.deaths

In [20]:
# deaths_prepped = results.process_deaths(results.data.deaths)
# deaths_prepped

# Preprocess MSLT results

In [21]:
!ls $mslt_output_dir

v4_2026_01_14_outside_sim_results_draw_level.csv
v4_2026_02_03_outside_sim_results_draw_level.csv
v4_2026_02_18_outside_sim_results_draw_level.csv
v4_2026_02_26_outside_sim_results_draw_level.csv

In [22]:
mslt_results = pd.read_csv(mslt_output_dir / 'v4_2026_02_26_outside_sim_results_draw_level.csv', index_col=0)
mslt_results

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Draw,Value
0,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_1,0.000000
1,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_103,0.000000
2,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_122,0.000000
3,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_123,0.000000
4,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_161,0.000000
...,...,...,...,...,...,...,...,...,...,...
113995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_50,2015.073423
113996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_6,1966.509895
113997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_63,2025.659827
113998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_69,2127.428568
113999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_7,2046.368615

In [23]:
mslt_results.Age.unique()

array(['65_to_69', '70_to_74', '75_to_79'], dtype=object)

In [24]:
mslt_results.Draw.unique()

array(['draw_1', 'draw_103', 'draw_122', 'draw_123', 'draw_161',
       'draw_172', 'draw_183', 'draw_187', 'draw_199', 'draw_204',
       'draw_211', 'draw_219', 'draw_235', 'draw_236', 'draw_24',
       'draw_245', 'draw_248', 'draw_249', 'draw_35', 'draw_41',
       'draw_50', 'draw_6', 'draw_63', 'draw_69', 'draw_7'], dtype=object)

In [25]:
mslt_results.Scenario.unique()

array(['BBBM Testing Only', 'BBBM Testing and Treatment'], dtype=object)

In [26]:
mslt_results_prepped = results.process_mslt_results(mslt_results)
mslt_results_prepped

,input_draw,location,age_group,disease_stage,event_year,measure,metric,scenario,sex,value
0,1,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Female,0.000000
1,1,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Female,0.000000
2,1,Brazil,75_to_79,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Female,0.000000
3,1,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Male,0.000000
4,1,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Male,0.000000
...,...,...,...,...,...,...,...,...,...,...
683995,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Female,648.594446
683996,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Female,627.810266
683997,249,United States of America,65_to_69,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Male,786.064602
683998,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Male,592.328371
683999,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Male,573.347234

In [27]:
mslt_results_prepped.measure.unique()

['BBBM Tests', 'Positive BBBM Tests', 'Medication Initiation']
Categories (3, object): ['BBBM Tests', 'Medication Initiation', 'Positive BBBM Tests']

# BBBM Test Counts

In [28]:
filename = 'counts_bbbm_tests'
# short_name = 'bbbm_tests'
with Timer():
    bbbm_tests = results.load_measure_from_batch_runs(
        filename, False, filters=loading.FINAL_RESULTS_FILTERS[filename])

bbbm_tests

Timer BatchLoadingTimer started
[('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
186.059997 MB after read_parquet
1.209888 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch3/model_spec/2026_02_13_17_10_34/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch2/model_spec/2026_02_13_15_02_52/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch10/model_spec/2026_02_14_06_55_09/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch6/model_spec/2026_02_13_18_33_24/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch7/model_spec/2026_02_13_21_04_24/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch4/model_spec/2026_02_13_17_14_14/results')}
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
10.038048 MB total
10.038048 MB after enforcing dtypes
Elapsed time: 51.4167 seconds
Elapsed time: 0:00:51.416934

,age_group,artifact_path,bbbm_test_results,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing,Female,,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing,Male,,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing_and_treatment,Female,,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing_and_treatment,Male,,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,187,counts_bbbm_tests,bbbm_testing,Female,,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
455995,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,1,counts_bbbm_tests,bbbm_testing_and_treatment,Male,,14465.0,Brazil
455996,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,211,counts_bbbm_tests,bbbm_testing,Female,,24094.0,Brazil
455997,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,211,counts_bbbm_tests,bbbm_testing,Male,,10437.0,Brazil
455998,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,211,counts_bbbm_tests,bbbm_testing_and_treatment,Female,,24094.0,Brazil
455999,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,211,counts_bbbm_tests,bbbm_testing_and_treatment,Male,,10437.0,Brazil

In [29]:
bbbm_tests.age_group.unique()

['65_to_69', '70_to_74', '75_to_79']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [30]:
bbbm_tests.query("value>0").age_group.unique()

['65_to_69', '70_to_74', '75_to_79']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [31]:
bbbm_tests.bbbm_test_results.unique()

['positive', 'negative']
Categories (3, object): ['negative', 'not_tested', 'positive']

In [32]:
bbbm_tests.query("value>0").scenario.unique()

['bbbm_testing', 'bbbm_testing_and_treatment']
Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [33]:
bbbm_tests_prepped = results.process_bbbm_tests(bbbm_tests, mslt_results_prepped)
bbbm_tests_prepped

,age_group,event_year,input_draw,location,measure,scenario,sex,value,disease_stage,metric
0,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
1,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Male,0.000000,Preclinical AD,Number
2,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Female,0.000000,Preclinical AD,Number
3,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Male,0.000000,Preclinical AD,Number
4,65_to_69,2025,6,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
...,...,...,...,...,...,...,...,...,...,...
911995,70_to_74,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Female,818.493948,Susceptible,Number
911996,75_to_79,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Female,792.265345,Susceptible,Number
911997,65_to_69,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Male,991.974449,Susceptible,Number
911998,70_to_74,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Male,747.488957,Susceptible,Number
911999,75_to_79,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Male,723.535706,Susceptible,Number

In [34]:
bbbm_tests_prepped.disease_stage.unique()

['Preclinical AD', 'Susceptible']
Categories (2, object): ['Preclinical AD', 'Susceptible']

In [35]:
bbbm_tests_prepped.measure.unique()

['BBBM Tests', 'Positive BBBM Tests']
Categories (2, object): ['BBBM Tests', 'Positive BBBM Tests']

In [36]:
with Timer():
    # bbbm_tests_output = results.summarize_and_beautify(bbbm_tests_prepped, 'disease_stage')
    bbbm_tests_output = results.do_final_processing(bbbm_tests_prepped, include_draws=True)
bbbm_tests_output
# 121600 rows

2026-03-09 17:29:15.894914
Timer SummarizingTimer started
Elapsed time: 103.0640 seconds
2026-03-09 17:31:07.264440
Elapsed time: 0:01:51.369597

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145915,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000250,0.000245,...,0.000251,0.000249,0.000253,0.000250,0.000246,0.000247,0.000252,0.000252,0.000253,0.000244
145916,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000237,0.000233,...,0.000236,0.000237,0.000238,0.000234,0.000235,0.000235,0.000239,0.000238,0.000241,0.000232
145917,2100,United States of America,65_plus,Female,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000226,0.000221,...,0.000223,0.000227,0.000225,0.000222,0.000225,0.000225,0.000227,0.000227,0.000232,0.000221
145918,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000250,0.000245,...,0.000251,0.000249,0.000253,0.000250,0.000246,0.000247,0.000252,0.000251,0.000253,0.000244
145919,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000237,0.000233,...,0.000236,0.000237,0.000238,0.000234,0.000234,0.000235,0.000238,0.000238,0.000241,0.000231

In [37]:
bbbm_tests_output.Measure.unique()

['BBBM Tests', 'Positive BBBM Tests']
Categories (2, object): ['BBBM Tests', 'Positive BBBM Tests']

In [38]:
bbbm_tests_output.Age.unique()

['65_to_69', '70_to_74', '75_to_79', '65_plus']
Categories (4, object): ['65_plus', '65_to_69', '70_to_74', '75_to_79']

In [39]:
bbbm_tests_output.query("Mean>0").Scenario.unique()

['BBBM Testing Only', 'BBBM Testing and Treatment']
Categories (3, object): ['Reference', 'BBBM Testing Only', 'BBBM Testing and Treatment']

In [40]:
bbbm_tests_output.query(
    "Year == 2100 & Location == 'United States of America' & Age == '75_to_79' & Sex == 'Male' & `Disease Stage` == 'Susceptible' & Scenario == 'BBBM Testing Only' & Measure == 'Positive BBBM Tests'"
)

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
109429,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Number,2597.044405,2359.099291,...,2653.192471,2690.703018,2835.103210,2556.828375,2477.040248,2595.719250,2412.324818,2592.306548,2649.757436,2513.953624
109435,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000396,0.000391,...,0.000398,0.000395,0.000401,0.000398,0.000392,0.000393,0.000396,0.000399,0.000394,0.000391

### Testing some stuff...

In [41]:
# temp = results.do_final_processing(bbbm_tests_prepped)
# temp

In [42]:
# results.ops.assert_values_equal(temp, bbbm_tests_output, value_cols=['Mean', '95% UI Lower', '95% UI Upper'], check_exact=False)

In [43]:
# temp2 = results.do_final_processing(bbbm_tests_prepped, include_draws=False)
# temp2

In [44]:
# results.ops.assert_values_equal(temp2, bbbm_tests_output, value_cols=['Mean', '95% UI Lower', '95% UI Upper'], check_exact=False)

In [45]:
# temp3 = results.do_final_processing(bbbm_tests_prepped, include_draws=True)
# temp3

In [46]:
# results.ops.assert_values_equal(
#     temp3.drop(columns=[c for c in temp3.columns if c.startswith('draw_')]),
#     bbbm_tests_output, value_cols=['Mean', '95% UI Lower', '95% UI Upper'], check_exact=False)

In [47]:
# Save BBBM testing results
bbbm_tests_output.to_csv(output_dir / 'bbbm_tests.csv', index=False)

# CSF and PET Test Counts

In [48]:
# csf_pet_filters = [('testing_state', 'in', ['csf', 'pet'])]
filename = 'counts_baseline_tests_among_eligible'
with Timer():
    csf_pet_tests = results.load_measure_from_batch_runs(
        filename, False, filters=loading.FINAL_RESULTS_FILTERS[filename]
    )
print(len(csf_pet_tests), 'rows')
csf_pet_tests.head()

Timer BatchLoadingTimer started
[('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
1302.348135 MB after read_parquet
8.433066 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch3/model_spec/2026_02_13_17_10_34/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch2/model_spec/2026_02_13_15_02_52/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch10/model_spec/2026_02_14_06_55_09/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch6/model_spec/2026_02_13_18_33_24/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch7/model_spec/2026_02_13_21_04_24/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch4/model_spec/2026_02_13_17_14_14/results')}
868.236135 MB after read_parquet
5.624106 MB after aggregating seeds and converting dtypes
70.230186 MB total
70.230186 MB after enforcing dtypes
Elapsed time: 125.0616 seconds
Elapsed time: 0:02:05.061957
3192000 rows

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,testing_state,value,location
0,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Female,,csf,0.0,Japan
1,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Female,,pet,0.0,Japan
2,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Male,,csf,0.0,Japan
3,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Male,,pet,0.0,Japan
4,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,bbbm_testing,Female,,csf,0.0,Japan

In [49]:
csf_pet_tests.query("value>0").age_group.unique()

['30_to_34', '35_to_39', '40_to_44', '45_to_49', '50_to_54', ..., '75_to_79', '80_to_84', '85_to_89', '90_to_94', '95_plus']
Length: 14
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [50]:
csf_pet_tests_prepped = results.process_csf_pet_tests(csf_pet_tests)
csf_pet_tests_prepped

95.766297 MB measure
31.926297 MB minuend
63.846297 MB subtrahend
21.290452 MB minuend re-indexed
42.570452 MB subtrahend re-indexed
42.570512 MB difference
72.358429 MB difference with reset index
74.486754 MB final difference

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,testing_state,value,location,metric,disease_stage
0,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,CSF Tests,baseline,Female,,csf,0.0,Japan,Number,MCI due to AD
1,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,PET Tests,baseline,Female,,pet,0.0,Japan,Number,MCI due to AD
2,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,CSF Tests,baseline,Male,,csf,0.0,Japan,Number,MCI due to AD
3,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,PET Tests,baseline,Male,,pet,0.0,Japan,Number,MCI due to AD
4,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,CSF Tests,bbbm_testing,Female,,csf,0.0,Japan,Number,MCI due to AD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5319995,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted PET Tests,bbbm_testing,Male,,pet,19.0,Brazil,Number,MCI due to AD
5319996,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted CSF Tests,bbbm_testing_and_treatment,Female,,csf,43.0,Brazil,Number,MCI due to AD
5319997,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted PET Tests,bbbm_testing_and_treatment,Female,,pet,68.0,Brazil,Number,MCI due to AD
5319998,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted CSF Tests,bbbm_testing_and_treatment,Male,,csf,14.0,Brazil,Number,MCI due to AD
5319999,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,211,Averted PET Tests,bbbm_testing_and_treatment,Male,,pet,19.0,Brazil,Number,MCI due to AD

In [51]:
# csf_pet_tests_output = results.summarize_and_beautify(csf_pet_tests_prepped, 'disease_stage')
csf_pet_tests_output = results.do_final_processing(csf_pet_tests_prepped, include_draws=True)
csf_pet_tests_output

2026-03-09 17:33:20.492422
Timer SummarizingTimer started
Elapsed time: 486.0896 seconds
2026-03-09 17:42:08.301692

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,Brazil,65_to_69,Female,MCI due to AD,Reference,CSF Tests,Number,3365.354044,1850.986316,...,5282.912217,1844.624657,2979.979069,2890.259512,2824.707602,3740.051078,1855.227421,4462.396099,2714.170045,3517.471481
1,2025,Brazil,65_to_69,Male,MCI due to AD,Reference,CSF Tests,Number,1320.010850,814.662530,...,1982.309716,924.667169,1269.471083,1436.344773,908.048937,1570.477324,723.874265,1800.744785,1048.693791,1350.732489
2,2025,Brazil,65_to_69,Both,MCI due to AD,Reference,CSF Tests,Number,4685.364895,2693.215770,...,7265.221933,2769.291826,4249.450152,4326.604285,3732.756539,5310.528403,2579.101686,6263.140884,3762.863835,4868.203969
3,2025,Brazil,65_to_69,Female,MCI due to AD,BBBM Testing Only,CSF Tests,Number,3365.354044,1850.986316,...,5282.912217,1844.624657,2979.979069,2890.259512,2824.707602,3740.051078,1855.227421,4462.396099,2714.170045,3517.471481
4,2025,Brazil,65_to_69,Male,MCI due to AD,BBBM Testing Only,CSF Tests,Number,1320.010850,814.662530,...,1982.309716,924.667169,1269.471083,1436.344773,908.048937,1570.477324,723.874265,1800.744785,1048.693791,1350.732489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683995,2100,United States of America,65_plus,Male,MCI due to AD,BBBM Testing Only,Averted PET Tests,Rate,0.000418,0.000187,...,0.000396,0.000485,0.000323,0.000473,0.000405,0.000295,0.000368,0.000614,0.000381,0.000239
683996,2100,United States of America,65_plus,Both,MCI due to AD,BBBM Testing Only,Averted PET Tests,Rate,0.000558,0.000269,...,0.000529,0.000632,0.000453,0.000655,0.000511,0.000424,0.000477,0.000774,0.000542,0.000356
683997,2100,United States of America,65_plus,Female,MCI due to AD,BBBM Testing and Treatment,Averted PET Tests,Rate,0.000672,0.000337,...,0.000638,0.000755,0.000559,0.000803,0.000599,0.000530,0.000566,0.000905,0.000676,0.000452
683998,2100,United States of America,65_plus,Male,MCI due to AD,BBBM Testing and Treatment,Averted PET Tests,Rate,0.000418,0.000187,...,0.000396,0.000484,0.000323,0.000473,0.000404,0.000295,0.000368,0.000613,0.000381,0.000239
683999,2100,United States of America,65_plus,Both,MCI due to AD,BBBM Testing and Treatment,Averted PET Tests,Rate,0.000557,0.000269,...,0.000529,0.000631,0.000453,0.000655,0.000511,0.000424,0.000477,0.000773,0.000542,0.000356

In [52]:
# Save CSF/PET testing results
csf_pet_tests_output.to_csv(output_dir / 'csf_pet_tests.csv', index=False)

# Treatment Counts

We count treatments using treatment transition counts in older models, and with the treatment duration counts starting in model 11.0

In [53]:
# treatments_filters = [
#     ('sub_entity', 'in',
#      ['susceptible_to_treatment_to_waiting_for_treatment',
#       'waiting_for_treatment_to_full_effect_long',
#       'waiting_for_treatment_to_full_effect_short']
#     )
# ]
treatment_transitions_filename = 'transition_count_treatment'

with Timer():
    treatment_transitions = results.load_measure_from_batch_runs(
        treatment_transitions_filename, False, 
        filters=loading.FINAL_RESULTS_FILTERS[treatment_transitions_filename]
    )
print(len(treatment_transitions), 'rows')
treatment_transitions.head()

Timer BatchLoadingTimer started
[('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84']), ('scenario', '==', 'bbbm_testing_and_treatment')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
60.204194 MB after read_parquet
0.389285 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch3/model_spec/2026_02_13_17_10_34/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch2/model_spec/2026_02_13_15_02_52/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch10/model_spec/2026_02_14_06_55_09/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch6/model_spec/2026_02_13_18_33_24/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch7/model_spec/2026_02_13_21_04_24/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch4/model_spec/2026_02_13_17_14_14/results')}
40.140194 MB after read_parquet
0.261605 MB after aggregating seeds and converting dtypes
3.198245 MB total
3.198245 MB after enforcing dtypes
Elapsed time: 75.8344 seconds
Elapsed time: 0:01:15.834863
152000 rows

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,transition_count,bbbm_testing_and_treatment,Female,waiting_for_treatment_to_treatment_effect,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,transition_count,bbbm_testing_and_treatment,Male,waiting_for_treatment_to_treatment_effect,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,187,transition_count,bbbm_testing_and_treatment,Female,waiting_for_treatment_to_treatment_effect,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,187,transition_count,bbbm_testing_and_treatment,Male,waiting_for_treatment_to_treatment_effect,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2026,35,transition_count,bbbm_testing_and_treatment,Female,waiting_for_treatment_to_treatment_effect,0.0,Japan

In [54]:
treatment_transitions.sub_entity.unique()

['waiting_for_treatment_to_treatment_effect']
Categories (5, object): ['susceptible_to_treatment_to_no_effect_never_t..., 'susceptible_to_treatment_to_waiting_for_treat..., 'treatment_effect_to_waning_effect', 'waiting_for_treatment_to_treatment_effect', 'waning_effect_to_no_effect_after_treatment']

In [55]:
treatment_transitions.query("value>0").scenario.unique()

['bbbm_testing_and_treatment']
Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [56]:
treatment_months_filename = 'treatment_duration'
# treatment_months_filters = [
#     ('sub_entity', '!=', 0),
#     ('age_group', 'in', loading.TESTING_ELIGIBLE_AGE_GROUPS),
#     # ('scenario', '==', 'bbbm_testing_and_treatment'),
# ] 

with Timer():
    treatment_months = results.load_measure_from_batch_runs(
        treatment_months_filename, False,
        filters=loading.FINAL_RESULTS_FILTERS[treatment_months_filename]
    )
print(len(treatment_months), 'rows')
treatment_months.head()

Timer BatchLoadingTimer started
[('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
492.491529 MB after read_parquet
2.591472 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch3/model_spec/2026_02_13_17_10_34/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch2/model_spec/2026_02_13_15_02_52/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch10/model_spec/2026_02_14_06_55_09/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch6/model_spec/2026_02_13_18_33_24/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch7/model_spec/2026_02_13_21_04_24/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch4/model_spec/2026_02_13_17_14_14/results')}
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
21.551952 MB total
21.551952 MB after enforcing dtypes
Elapsed time: 144.0794 seconds
Elapsed time: 0:02:24.079607
1026000 rows

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan

In [57]:
treatment_months.query("value>0").sub_entity.unique()

[1, 6, 9, 7, 3, 4, 8, 2, 5]
Categories (9, int64): [1, 2, 3, 4, ..., 6, 7, 8, 9]

In [58]:
treatment_months.query("value>0").scenario.unique()

['bbbm_testing_and_treatment']
Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [59]:
start_treatment = [
        'waiting_for_treatment_to_full_effect_long',
        'waiting_for_treatment_to_full_effect_short',
        'waiting_for_treatment_to_treatment_effect']
treatment_transitions.query("sub_entity in @start_treatment and value>0").age_group.unique()

['65_to_69', '70_to_74', '75_to_79', '80_to_84']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [60]:
# # Now empty because we filter out this transition on loading
# treatments.query("sub_entity=='susceptible_to_treatment_to_waiting_for_treatment' and value>0").age_group.unique()
# # Should be ['60_to_64', '65_to_69', '70_to_74', '75_to_79']

In [61]:
# Check which transitions are present in the treatment transitions
# dataframe, to determine whether we should use treatment transition
# counts or treatment duration counts to count completed vs.
# discontinued treatments
unique_transitions = treatment_transitions['sub_entity'].unique()

if ('waiting_for_treatment_to_full_effect_long' in unique_transitions
    and 'waiting_for_treatment_to_full_effect_short' in unique_transitions):
    treatments = treatment_transitions
elif 'waiting_for_treatment_to_treatment_effect' in unique_transitions:
    treatments = treatment_months
else:
    raise ValueError(
        f"Missing expected treatment transitions: {unique_transitions}")

treatments

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...
1025995,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,5,117.0,Brazil
1025996,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,6,95.0,Brazil
1025997,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,7,101.0,Brazil
1025998,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,8,109.0,Brazil
1025999,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,9,7602.0,Brazil

In [62]:
treatments_prepped = results.process_treatments(treatments, mslt_results_prepped)
treatments_prepped

,age_group,event_year,input_draw,location,scenario,sex,measure,value,disease_stage
0,65_to_69,2025,1,Japan,bbbm_testing_and_treatment,Female,Medication Discontinuation,0.0,Preclinical AD
1,65_to_69,2025,1,Japan,bbbm_testing_and_treatment,Female,Medication Completion,0.0,Preclinical AD
2,65_to_69,2025,1,Japan,bbbm_testing_and_treatment,Male,Medication Discontinuation,0.0,Preclinical AD
3,65_to_69,2025,1,Japan,bbbm_testing_and_treatment,Male,Medication Completion,0.0,Preclinical AD
4,65_to_69,2025,6,Japan,bbbm_testing_and_treatment,Female,Medication Discontinuation,0.0,Preclinical AD
...,...,...,...,...,...,...,...,...,...
341995,75_to_79,2100,245,Brazil,bbbm_testing_and_treatment,Male,Medication Initiation,10819.0,Preclinical AD
341996,75_to_79,2100,248,Brazil,bbbm_testing_and_treatment,Female,Medication Initiation,17851.0,Preclinical AD
341997,75_to_79,2100,248,Brazil,bbbm_testing_and_treatment,Male,Medication Initiation,7298.0,Preclinical AD
341998,75_to_79,2100,249,Brazil,bbbm_testing_and_treatment,Female,Medication Initiation,19814.0,Preclinical AD
341999,75_to_79,2100,249,Brazil,bbbm_testing_and_treatment,Male,Medication Initiation,9019.0,Preclinical AD

In [63]:
treatments_prepped.query("measure=='Medication Initiation'").disease_stage.unique()

['Preclinical AD']
Categories (1, object): ['Preclinical AD']

In [64]:
treatments_prepped.query("disease_stage=='Susceptible'").scenario.unique()

[], Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [65]:
treatments_prepped.query("scenario in ['BBBM Testing Only', 'bbbm_testing']").value.unique()

array([], dtype=float64)

In [66]:
with Timer():
    # treatments_output = results.summarize_and_beautify(treatments_prepped, 'disease_stage')
    treatments_output = results.do_final_processing(treatments_prepped, include_draws=True)

print(len(treatments_output), 'rows')
treatments_output.head()

2026-03-09 17:46:04.904344
Timer SummarizingTimer started
Elapsed time: 38.9194 seconds
2026-03-09 17:46:48.791904
Elapsed time: 0:00:43.887629
54720 rows

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
treatments_output.query(
    "Year == 2100 & Location == 'United States of America' & Age == '75_to_79' & Sex == 'Male' & `Disease Stage` == 'Susceptible' & Scenario == 'BBBM Testing and Treatment' & Measure == 'Medication Initiation'"
)
# orig mean: 93092.973924
# new mean: 41049.447242

Empty DataFrame
Columns: [Year, Location, Age, Sex, Disease Stage, Scenario, Measure, Metric, Mean, 95% UI Lower, 95% UI Upper, draw_1, draw_6, draw_7, draw_24, draw_35, draw_41, draw_50, draw_63, draw_69, draw_103, draw_122, draw_123, draw_161, draw_172, draw_183, draw_187, draw_199, draw_204, draw_211, draw_219, draw_235, draw_236, draw_245, draw_248, draw_249]
Index: []

[0 rows x 36 columns]

In [68]:
41049.447242 / 93092.973924

0.4409510783865631

In [69]:
treatments_output.isna().any().any()

False

In [70]:
# Save treatments output
treatments_output.to_csv(output_dir / 'medication.csv', index=False)

# Process months of treatment

In [71]:
treatment_months
# Needed columns:
# year, location, age group, sex, scenario, sub-entity (months of treatment), value (count)

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...
1025995,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,5,117.0,Brazil
1025996,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,6,95.0,Brazil
1025997,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,7,101.0,Brazil
1025998,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,8,109.0,Brazil
1025999,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,211,treatment_duration_count,bbbm_testing_and_treatment,Male,9,7602.0,Brazil

In [72]:
treatment_months_prepped = results.process_months_of_treatment(treatment_months)
treatment_months_prepped

,age_group,event_year,input_draw,measure,scenario,sex,doses_completed,value,location,metric,disease_stage
0,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,1,0,Japan,Number,Preclinical AD
1,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,2,0,Japan,Number,Preclinical AD
2,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,3,0,Japan,Number,Preclinical AD
3,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,4,0,Japan,Number,Preclinical AD
4,65_to_69,2025,35,Medication by number of doses completed,bbbm_testing_and_treatment,Female,5,0,Japan,Number,Preclinical AD
...,...,...,...,...,...,...,...,...,...,...,...
1025995,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,5,117,Brazil,Number,Preclinical AD
1025996,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,6,95,Brazil,Number,Preclinical AD
1025997,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,7,101,Brazil,Number,Preclinical AD
1025998,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,8,109,Brazil,Number,Preclinical AD
1025999,75_to_79,2100,211,Medication by number of doses completed,bbbm_testing_and_treatment,Male,9,7602,Brazil,Number,Preclinical AD

In [73]:
treatment_months_output = results.do_final_processing(treatment_months_prepped, include_draws=True)
treatment_months_output

2026-03-09 17:46:50.761580
Timer SummarizingTimer started
Elapsed time: 114.9448 seconds
2026-03-09 17:48:54.812171

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Doses Completed,Mean,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164155,2100,United States of America,65_plus,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,9,49719.422008,...,54454.245433,56943.517821,54084.857551,46983.824892,53108.150817,47446.992696,48813.107239,56001.113960,46599.328480,44567.922289
164156,2100,United States of America,65_plus,Both,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,9,139912.504418,...,149433.635072,154478.700673,157518.574777,139863.328269,144371.637040,141936.196273,136776.219435,147093.086609,142728.947015,137675.165883
164157,2100,United States of America,65_plus,Female,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,9,0.002106,...,0.002178,0.002238,0.002218,0.002171,0.002222,0.002186,0.002220,0.002143,0.002253,0.002196
164158,2100,United States of America,65_plus,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,9,0.001404,...,0.001515,0.001546,0.001419,0.001348,0.001548,0.001326,0.001497,0.001595,0.001305,0.001269
164159,2100,United States of America,65_plus,Both,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,9,0.001788,...,0.001878,0.001921,0.001859,0.001801,0.001915,0.001797,0.001894,0.001895,0.001821,0.001776

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Doses Completed,Mean,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,1,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164155,2100,United States of America,65_plus,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,9,49719.422008,...,54454.245433,56943.517821,54084.857551,46983.824892,53108.150817,47446.992696,48813.107239,56001.113960,46599.328480,44567.922289
164156,2100,United States of America,65_plus,Both,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Number,9,139912.504418,...,149433.635072,154478.700673,157518.574777,139863.328269,144371.637040,141936.196273,136776.219435,147093.086609,142728.947015,137675.165883
164157,2100,United States of America,65_plus,Female,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,9,0.002106,...,0.002178,0.002238,0.002218,0.002171,0.002222,0.002186,0.002220,0.002143,0.002253,0.002196
164158,2100,United States of America,65_plus,Male,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,9,0.001404,...,0.001515,0.001546,0.001419,0.001348,0.001548,0.001326,0.001497,0.001595,0.001305,0.001269
164159,2100,United States of America,65_plus,Both,Preclinical AD,BBBM Testing and Treatment,Medication by number of doses completed,Rate,9,0.001788,...,0.001878,0.001921,0.001859,0.001801,0.001915,0.001797,0.001894,0.001895,0.001821,0.001776

In [74]:
treatment_months_output.isna().any().any()

False

In [75]:
# Save months of treatment output
# 41M when including 4 draws, 106M with 25 draws
treatment_months_output.to_csv(output_dir / 'medication_doses.csv', index=False)

# Check some stuff

In [76]:
!ls -halt $output_dir

total 2.1G
-rw-rw-r-- 1 ndbs       Domain Users 106M Mar  9 17:48 medication_doses.csv
-rw-rw-r-- 1 ndbs       Domain Users  35M Mar  9 17:46 medication.csv
-rw-rw-r-- 1 ndbs       Domain Users 341M Mar  9 17:42 csf_pet_tests.csv
-rw-rw-r-- 1 ndbs       Domain Users  88M Mar  9 17:31 bbbm_tests.csv
-rw-rw-r-- 1 ndbs       Domain Users 474M Mar  4 11:30 prevalence.csv
-rw-rw-r-- 1 ndbs       Domain Users 156M Mar  4 11:06 deaths.csv
-rw-rw-r-- 1 ndbs       Domain Users  57M Mar  4 10:56 population.csv
-rw-rw-r-- 1 ndbs       Domain Users 339M Mar  3 20:40 incidence.csv
-rw-rw-r-- 1 ndbs       Domain Users 389M Mar  3 20:22 dalys.csv
drwxrwxr-x 7 ndbs       Domain Users    0 Feb 27 18:31 .
drwxrwxr-x 2 ndbs       Domain Users    0 Feb 26 20:53 version5
drwxrwxr-x 2 ndbs       Domain Users    0 Feb 26 20:43 version4
drwxrwxr-x 2 ndbs       Domain Users    0 Feb 26 20:41 version3
drwxrwxrwx 7 2074479877    310492440    0 Dec  4 13:19 ..
drwxrwxr-x 2 ndbs       Domain Users    0 Nov 24 20:19 version2
drwxrwxr-x 2 ndbs       Domain Users    0 Nov 17 11:53 version1

In [77]:
treatments_output

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Number,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,Medication Discontinuation,Rate,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54715,2100,United States of America,65_plus,Male,Preclinical AD,BBBM Testing and Treatment,Medication Initiation,Number,55229.094536,47303.531308,...,60474.065903,63247.659068,60257.931060,52358.829962,58922.331579,52661.749406,54175.311277,61987.157877,51610.088547,49394.058101
54716,2100,United States of America,65_plus,Both,Preclinical AD,BBBM Testing and Treatment,Medication Initiation,Number,155498.278836,139131.995247,...,165924.844445,171562.145164,175176.343889,155597.633193,160123.044090,157861.260996,152062.502590,163218.224788,158679.003063,152685.177911
54717,2100,United States of America,65_plus,Female,Preclinical AD,BBBM Testing and Treatment,Medication Initiation,Rate,0.002341,0.002170,...,0.002418,0.002485,0.002465,0.002413,0.002464,0.002434,0.002471,0.002381,0.002509,0.002437
54718,2100,United States of America,65_plus,Male,Preclinical AD,BBBM Testing and Treatment,Medication Initiation,Rate,0.001560,0.001351,...,0.001683,0.001717,0.001581,0.001502,0.001718,0.001472,0.001661,0.001765,0.001445,0.001406
54719,2100,United States of America,65_plus,Both,Preclinical AD,BBBM Testing and Treatment,Medication Initiation,Rate,0.001987,0.001819,...,0.002086,0.002133,0.002067,0.002004,0.002124,0.001998,0.002105,0.002103,0.002024,0.001970

In [78]:
treatments_output.query("`Disease Stage` == 'Preclinical AD'").Year.unique()

[2025, 2026, 2027, 2028, 2029, ..., 2096, 2097, 2098, 2099, 2100]
Length: 76
Categories (76, int64): [2025, 2026, 2027, 2028, ..., 2097, 2098, 2099, 2100]

In [79]:
treatments_prepped.age_group.unique()

['65_to_69', '70_to_74', '75_to_79']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [80]:
treatment_rates = results.calculate_rate(treatments_prepped)
treatment_rates

,age_group,event_year,input_draw,location,scenario,sex,disease_stage,measure,value,metric
0,65_to_69,2025,1,Brazil,baseline,Both,NaN,NaN,NaN,Rate
1,65_to_69,2025,1,Brazil,baseline,Female,NaN,NaN,NaN,Rate
2,65_to_69,2025,1,Brazil,baseline,Male,NaN,NaN,NaN,Rate
3,65_to_69,2025,1,Brazil,bbbm_testing,Both,NaN,NaN,NaN,Rate
4,65_to_69,2025,1,Brazil,bbbm_testing,Female,NaN,NaN,NaN,Rate
...,...,...,...,...,...,...,...,...,...,...
740995,75_to_79,2100,249,United States of America,bbbm_testing_and_treatment,Female,Preclinical AD,Medication Completion,0.001255,Rate
740996,75_to_79,2100,249,United States of America,bbbm_testing_and_treatment,Female,Preclinical AD,Medication Initiation,0.001392,Rate
740997,75_to_79,2100,249,United States of America,bbbm_testing_and_treatment,Male,Preclinical AD,Medication Discontinuation,0.000086,Rate
740998,75_to_79,2100,249,United States of America,bbbm_testing_and_treatment,Male,Preclinical AD,Medication Completion,0.000824,Rate
740999,75_to_79,2100,249,United States of America,bbbm_testing_and_treatment,Male,Preclinical AD,Medication Initiation,0.000909,Rate

In [81]:
treatment_rates.query("disease_stage=='Susceptible'")

Empty DataFrame
Columns: [age_group, event_year, input_draw, location, scenario, sex, disease_stage, measure, value, metric]
Index: []

In [82]:
mslt_results_prepped.query("measure.str.contains('Medication')")

,input_draw,location,age_group,disease_stage,event_year,measure,metric,scenario,sex,value
912,1,Brazil,65_to_69,Susceptible,2025,Medication Initiation,Number,bbbm_testing,Female,0.000000
913,1,Brazil,70_to_74,Susceptible,2025,Medication Initiation,Number,bbbm_testing,Female,0.000000
914,1,Brazil,75_to_79,Susceptible,2025,Medication Initiation,Number,bbbm_testing,Female,0.000000
915,1,Brazil,65_to_69,Susceptible,2025,Medication Initiation,Number,bbbm_testing,Male,0.000000
916,1,Brazil,70_to_74,Susceptible,2025,Medication Initiation,Number,bbbm_testing,Male,0.000000
...,...,...,...,...,...,...,...,...,...,...
683995,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Female,648.594446
683996,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Female,627.810266
683997,249,United States of America,65_to_69,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Male,786.064602
683998,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Male,592.328371
683999,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Male,573.347234

In [83]:
mslt_results_prepped.measure.unique()

['BBBM Tests', 'Positive BBBM Tests', 'Medication Initiation']
Categories (3, object): ['BBBM Tests', 'Medication Initiation', 'Positive BBBM Tests']

# Scratchwork

In [84]:
bbbm_tests_prepped

,age_group,event_year,input_draw,location,measure,scenario,sex,value,disease_stage,metric
0,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
1,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Male,0.000000,Preclinical AD,Number
2,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Female,0.000000,Preclinical AD,Number
3,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Male,0.000000,Preclinical AD,Number
4,65_to_69,2025,6,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
...,...,...,...,...,...,...,...,...,...,...
911995,70_to_74,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Female,818.493948,Susceptible,Number
911996,75_to_79,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Female,792.265345,Susceptible,Number
911997,65_to_69,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Male,991.974449,Susceptible,Number
911998,70_to_74,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Male,747.488957,Susceptible,Number
911999,75_to_79,2100,249,United States of America,Positive BBBM Tests,bbbm_testing_and_treatment,Male,723.535706,Susceptible,Number

In [85]:
column_name_map = {
            'event_year': 'Year',
            'age_group': 'Age',
            'location': 'Location',
            'sex': 'Sex',
            'scenario': 'Scenario',
            'measure': 'Measure',
            'metric': 'Metric',
            'disease_stage': 'Disease Stage',
            'input_draw': 'Draw',
            'value': 'Value',
            'mean': 'Mean',
            'lower': '95% UI Lower',
            'upper': '95% UI Upper',
        }
reverse_map = {v: k for k, v in column_name_map.items()}
reverse_map

{'Year': 'event_year',
 'Age': 'age_group',
 'Location': 'location',
 'Sex': 'sex',
 'Scenario': 'scenario',
 'Measure': 'measure',
 'Metric': 'metric',
 'Disease Stage': 'disease_stage',
 'Draw': 'input_draw',
 'Value': 'value',
 'Mean': 'mean',
 '95% UI Lower': 'lower',
 '95% UI Upper': 'upper'}

In [86]:
temp = mslt_results.rename(columns=reverse_map)
temp

,event_year,location,age_group,sex,disease_stage,scenario,measure,metric,input_draw,value
0,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_1,0.000000
1,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_103,0.000000
2,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_122,0.000000
3,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_123,0.000000
4,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_161,0.000000
...,...,...,...,...,...,...,...,...,...,...
113995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_50,2015.073423
113996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_6,1966.509895
113997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_63,2025.659827
113998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_69,2127.428568
113999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_7,2046.368615

In [87]:
pd.concat([bbbm_tests_prepped, temp])

,age_group,event_year,input_draw,location,measure,scenario,sex,value,disease_stage,metric
0,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
1,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing,Male,0.000000,Preclinical AD,Number
2,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Female,0.000000,Preclinical AD,Number
3,65_to_69,2025,1,Japan,BBBM Tests,bbbm_testing_and_treatment,Male,0.000000,Preclinical AD,Number
4,65_to_69,2025,6,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
...,...,...,...,...,...,...,...,...,...,...
113995,75_to_79,2100,draw_50,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,2015.073423,Susceptible,Number
113996,75_to_79,2100,draw_6,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,1966.509895,Susceptible,Number
113997,75_to_79,2100,draw_63,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,2025.659827,Susceptible,Number
113998,75_to_79,2100,draw_69,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,2127.428568,Susceptible,Number
113999,75_to_79,2100,draw_7,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,2046.368615,Susceptible,Number

In [88]:
temp.query("measure.str.contains('Medication') and value > 0 and scenario=='BBBM Testing Only'")

,event_year,location,age_group,sex,disease_stage,scenario,measure,metric,input_draw,value
300,2027,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_1,2.309480
301,2027,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_103,2.334837
302,2027,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_122,2.126360
303,2027,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_123,2.173761
304,2027,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_161,2.028779
...,...,...,...,...,...,...,...,...,...,...
113995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_50,2015.073423
113996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_6,1966.509895
113997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_63,2025.659827
113998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_69,2127.428568
113999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_7,2046.368615

In [89]:
temp.measure.unique()

array(['BBBM Tests', 'BBBM False Positive Tests',
       'Improper Medication Uses'], dtype=object)

In [90]:
temp.replace(
    {'measure': {'BBBM False Positive Tests': 'BBBM Positive Tests',
 'Improper Medication Uses': 'Medication Initiation'}})

,event_year,location,age_group,sex,disease_stage,scenario,measure,metric,input_draw,value
0,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_1,0.000000
1,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_103,0.000000
2,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_122,0.000000
3,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_123,0.000000
4,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_161,0.000000
...,...,...,...,...,...,...,...,...,...,...
113995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_50,2015.073423
113996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_6,1966.509895
113997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_63,2025.659827
113998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_69,2127.428568
113999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_7,2046.368615

In [91]:
bbbm_tests_prepped.dtypes

age_group        category
event_year       category
input_draw       category
location         category
measure          category
scenario         category
sex              category
value             float64
disease_stage    category
metric           category
dtype: object

In [92]:
testing = temp.query("scenario=='BBBM Testing Only'").drop(columns='scenario')
treatment = temp.query("scenario=='BBBM Testing and Treatment'").drop(columns='scenario')
# This shows that the whole dataframe was copied to the testing-only
# scenario, including medication initiations, which is incorrect
results.ops.compare_values(testing, treatment)

Empty DataFrame
Columns: []
Index: []

In [93]:
mslt_results_processed = results.process_mslt_results(mslt_results)
mslt_results_processed

,input_draw,location,age_group,disease_stage,event_year,measure,metric,scenario,sex,value
0,1,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Female,0.000000
1,1,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Female,0.000000
2,1,Brazil,75_to_79,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Female,0.000000
3,1,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Male,0.000000
4,1,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,bbbm_testing,Male,0.000000
...,...,...,...,...,...,...,...,...,...,...
683995,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Female,648.594446
683996,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Female,627.810266
683997,249,United States of America,65_to_69,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Male,786.064602
683998,249,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Male,592.328371
683999,249,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,bbbm_testing_and_treatment,Male,573.347234

In [94]:
mslt_results_processed.input_draw.unique()

[1, 6, 7, 24, 35, ..., 235, 236, 245, 248, 249]
Length: 25
Categories (25, int64): [1, 6, 7, 24, ..., 236, 245, 248, 249]

In [95]:
print_memory_usage(mslt_results_processed)

11.634045 MB

In [96]:
mslt_results_processed.measure.unique()

['BBBM Tests', 'Positive BBBM Tests', 'Medication Initiation']
Categories (3, object): ['BBBM Tests', 'Medication Initiation', 'Positive BBBM Tests']

In [97]:
!date

Mon 09 Mar 2026 05:49:07 PM PDT