In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt

import os
from pathlib import Path

from vivarium_helpers.utils import convert_to_categorical, constant_categorical, print_memory_usage, Timer

from vivarium_helpers.projects.alzheimers import loading, population
from vivarium_helpers.projects.alzheimers.population import RunType
from vivarium_helpers.projects.alzheimers.results import AlzheimersResultsProcessor

!date
!whoami
!pwd

Wed Mar  4 10:51:23 PST 2026
ndbs
/mnt/share/code/ndbs/vivarium_research_alzheimers/results_tables

# Record version of Vivarium Helpers

In [3]:
!conda list | grep vivarium

# packages in environment at /ihme/homes/ndbs/miniconda3/envs/vivarium_csu_alzheimers_artifact:
vivarium                  3.4.12                   pypi_0    pypi
vivarium-build-utils      2.0.4                    pypi_0    pypi
vivarium-cluster-tools    2.1.17                   pypi_0    pypi
vivarium-csu-alzheimers   0.1.dev18+g43e997c.d20250808          pypi_0    pypi
vivarium-dependencies     1.0.1                    pypi_0    pypi
vivarium-gbd-access       4.2.4                    pypi_0    pypi
vivarium-helpers          0.2.0                     dev_0    <develop>
vivarium-inputs           6.0.4                    pypi_0    pypi
vivarium-public-health    4.3.5                    pypi_0    pypi

In [4]:
!pip freeze | grep vivarium

vivarium==3.4.12
vivarium_build_utils==2.0.4
vivarium_cluster_tools==2.1.17
-e git+https://github.com/ihmeuw/vivarium_csu_alzheimers.git@263eb3d9b80b13735a7380bb892430eaba92603a#egg=vivarium_csu_alzheimers
vivarium_dependencies==1.0.1
vivarium_gbd_access==4.2.4
-e git+https://github.com/ihmeuw/vivarium_helpers.git@eaebc2562ba8cec23a89089d3f659e4e1491e23f#egg=vivarium_helpers
vivarium_inputs==6.0.4
vivarium_public_health==4.3.5

# Define data directories

In [5]:
# Project directory
project_dir = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/')

# Output directory to store final results for client
output_dir = Path(r"J:\Project\simulation_science\alzheimers\results_in_progress".replace('\\', '/').replace('J:', '/snfs1'))
print(output_dir.exists())

# Output from multistate life table
# mslt_output_dir = output_dir.parent / 'results_11_14_2025_mslt'
mslt_output_dir = project_dir / 'results' / 'mslt_draws'
print(mslt_output_dir.exists())
output_dir

True
True

PosixPath('/snfs1/Project/simulation_science/alzheimers/results_in_progress')

In [6]:
# # For testing: Run directory containing model 8.3 results for all
# # locations
# model_run_subdir = 'results/abie_consistent_model_test/united_states_of_america/2025_10_28_08_55_05/'

# # Results directory for model 8.3, for testing
# results_dirs = project_dir / model_run_subdir / 'results/'

# Artifact for models 10.0 - 12.2
artifact_model_number = '10.0'

In [7]:
# Model 8.4 results (final runs for 10/31/25 intermediate results)
# Each batch run contains all locations, 100 random seeds, and 3 or 4 draws
model_run_dir_8_4 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model8.4/model_spec')

# Model 8.7 results (updated final run completed on 11/10/2025)
model_run_dir_8_7 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model8.7/model_spec')

# Model 12.2 results (updated final run completed on 02/14/2026)
model_run_dir_12_2 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2')

# Batch runs are stored in "timestamp" subdirectories of the model run
# directory.
# In model 12.2, the run directories are nested under two more levels of
# subfolders: batch number, then model_spec, then timestamp.

# Select a model and filter for testing
batch_run_dirs = loading.list_batch_run_directories(model_run_dir_12_2)#[:2]

batch_run_dirs

['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch3/model_spec/2026_02_13_17_10_34',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch2/model_spec/2026_02_13_15_02_52',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch10/model_spec/2026_02_14_06_55_09',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch6/model_spec/2026_02_13_18_33_24',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch7/model_spec/2026_02_13_21_04_24',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch4/model_spec/2026_02_13_17_14_14']

# Create an AlzheimersResultsProcessor object to process results

In [8]:
results = AlzheimersResultsProcessor('10.0', RunType.FINAL, batch_run_dirs=batch_run_dirs)

In [9]:
results.initial_simulation_population

2000000

In [10]:
results.locations

['United States of America',
 'Brazil',
 'China',
 'Germany',
 'Israel',
 'Japan',
 'Spain',
 'Sweden',
 'Taiwan (Province of China)',
 'United Kingdom']

In [11]:
results.draws

[35,
 187,
 41,
 123,
 248,
 122,
 183,
 103,
 161,
 50,
 24,
 172,
 235,
 245,
 69,
 204,
 219,
 63,
 199,
 6,
 249,
 7,
 236,
 1,
 211]

# Load population data and calculate model scale

In [12]:
with Timer():
    results.load_population_data(append_aggregates=False)
results.ops.describe(results.model_scale)

Elapsed time: 0:00:16.828028

,count,mean,std,min,25%,50%,75%,max
location,,,,,,,,
Brazil,25.0,0.645126,0.042517,0.544775,0.618288,0.636986,0.682593,0.718303
China,25.0,0.075453,0.003924,0.067459,0.072855,0.075736,0.077771,0.085044
Germany,25.0,0.548393,0.025209,0.498396,0.536829,0.546442,0.557773,0.604171
Israel,25.0,26.039578,2.496689,20.549962,24.481746,25.631266,28.245708,30.287894
Japan,25.0,0.354952,0.020849,0.308678,0.339599,0.355165,0.367604,0.399881
Spain,25.0,1.865326,0.083683,1.719458,1.822242,1.856133,1.887104,2.134511
Sweden,25.0,7.785869,0.522496,6.614222,7.413090,7.838525,8.131916,8.716418
Taiwan (Province of China),25.0,5.271920,0.276774,4.659120,5.108985,5.251648,5.484657,5.726114
United Kingdom,25.0,1.229875,0.047735,1.167644,1.185930,1.220243,1.267019,1.318293
United States of America,25.0,0.275399,0.015292,0.251900,0.264626,0.274222,0.284826,0.322825

In [13]:
results.person_time

,location,sex,event_year,input_draw,value,age_group
0,United States of America,Female,2025,35,1.164474e+07,25_to_29
1,United States of America,Female,2025,187,1.125975e+07,25_to_29
2,United States of America,Female,2025,41,1.126842e+07,25_to_29
3,United States of America,Female,2025,123,1.171134e+07,25_to_29
4,United States of America,Female,2025,248,1.149482e+07,25_to_29
...,...,...,...,...,...,...
569995,United Kingdom,Male,2100,249,1.432651e+05,95_plus
569996,United Kingdom,Male,2100,7,1.488699e+05,95_plus
569997,United Kingdom,Male,2100,236,1.018623e+05,95_plus
569998,United Kingdom,Male,2100,1,1.332201e+05,95_plus
569999,United Kingdom,Male,2100,211,1.360060e+05,95_plus

In [14]:
570000*2

1140000

In [15]:
results.person_time.input_draw.unique()

array([ 35, 187,  41, 123, 248, 122, 183, 103, 161,  50,  24, 172, 235,
       245,  69, 204, 219,  63, 199,   6, 249,   7, 236,   1, 211],
      dtype=int16)

In [16]:
results.person_time.age_group.unique()

['25_to_29', '30_to_34', '35_to_39', '40_to_44', '45_to_49', ..., '75_to_79', '80_to_84', '85_to_89', '90_to_94', '95_plus']
Length: 15
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

# Load prevalence and append counterfactual person-time

In [17]:
with Timer():
    results.load_prevalence_and_append_counterfactual_person_time(append_aggregates=True)
results.person_time

Timer BatchLoadingTimer started
[('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025')]
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025')]
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025')]
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025')]
1264.043928 MB after read_parquet
8.049819 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025')]
1896.059928 MB after read_parquet
12.071739 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}

,location,sex,event_year,input_draw,value,age_group,scenario
0,United States of America,Female,2025,35,1.097634e+07,65_to_69,baseline
1,United States of America,Female,2025,187,1.066321e+07,65_to_69,baseline
2,United States of America,Female,2025,41,1.063578e+07,65_to_69,baseline
3,United States of America,Female,2025,123,1.104572e+07,65_to_69,baseline
4,United States of America,Female,2025,248,1.080614e+07,65_to_69,baseline
...,...,...,...,...,...,...,...
2621995,United Kingdom,Both,2100,249,4.067978e+05,95_plus,bbbm_testing
2621996,United Kingdom,Both,2100,249,4.094528e+05,95_plus,bbbm_testing_and_treatment
2621997,United States of America,Both,2100,249,1.977824e+06,95_plus,baseline
2621998,United States of America,Both,2100,249,1.977824e+06,95_plus,bbbm_testing
2621999,United States of America,Both,2100,249,1.987725e+06,95_plus,bbbm_testing_and_treatment

In [18]:
results.person_time.age_group.unique()

array(['65_to_69', '70_to_74', '75_to_79', '80_to_84', '85_to_89',
       '90_to_94', '95_plus', '25_to_29', '30_to_34', '35_to_39',
       '40_to_44', '45_to_49', '50_to_54', '55_to_59', '60_to_64',
       '65_plus'], dtype=object)

In [19]:
# Check that population is the same in baseline and bbbm_testing
# scenarios, and that it's greater in the treatment scenario
# NOTE: The baseline scenario still includes the 25-29 age group, so the
# count is higher than the other scenarios
results.person_time.groupby('scenario').value.describe()

,count,mean,std,min,25%,50%,75%,max
scenario,,,,,,,,
baseline,912000.0,9.642169e+06,2.483514e+07,6042.697443,710022.674632,2.457002e+06,7.578084e+06,4.228458e+08
bbbm_testing,855000.0,9.764529e+06,2.543134e+07,6042.697443,697472.877547,2.446895e+06,7.467042e+06,4.228458e+08
bbbm_testing_and_treatment,855000.0,9.767815e+06,2.544382e+07,6042.697443,697564.022013,2.446933e+06,7.469401e+06,4.234925e+08

# Process population data for output

In [20]:
person_time_processed = results.process_person_time()
person_time_processed

,location,sex,event_year,input_draw,value,age_group,scenario,measure,metric
0,United States of America,Female,2025,35,1.097634e+07,65_to_69,baseline,Population,Number
1,United States of America,Female,2025,187,1.066321e+07,65_to_69,baseline,Population,Number
2,United States of America,Female,2025,41,1.063578e+07,65_to_69,baseline,Population,Number
3,United States of America,Female,2025,123,1.104572e+07,65_to_69,baseline,Population,Number
4,United States of America,Female,2025,248,1.080614e+07,65_to_69,baseline,Population,Number
...,...,...,...,...,...,...,...,...,...
2621995,United Kingdom,Both,2100,249,4.067978e+05,95_plus,bbbm_testing,Population,Number
2621996,United Kingdom,Both,2100,249,4.094528e+05,95_plus,bbbm_testing_and_treatment,Population,Number
2621997,United States of America,Both,2100,249,1.977824e+06,95_plus,baseline,Population,Number
2621998,United States of America,Both,2100,249,1.977824e+06,95_plus,bbbm_testing,Population,Number
2621999,United States of America,Both,2100,249,1.987725e+06,95_plus,bbbm_testing_and_treatment,Population,Number

In [21]:
person_time_processed.age_group.unique()

['65_to_69', '70_to_74', '75_to_79', '80_to_84', '85_to_89', ..., '45_to_49', '50_to_54', '55_to_59', '60_to_64', '65_plus']
Length: 15
Categories (15, object): ['30_to_34', '35_to_39', '40_to_44', '45_to_49', ..., '80_to_84', '85_to_89', '90_to_94', '95_plus']

In [22]:
# We don't need to scale up or append rates and aggregates to the
# population data, so we just summarize and beautify
person_time_output = (
    person_time_processed
    .pipe(results.summarize, include_draws=True)
    .pipe(results.beautify)
)
person_time_output

Timer SummarizingTimer started

Elapsed time: 123.3378 seconds

,Year,Location,Age,Sex,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,United States of America,65_to_69,Female,Reference,Population,Number,1.053025e+07,9.602182e+06,1.119637e+07,...,1.066321e+07,1.087770e+07,1.142234e+07,1.026845e+07,1.003314e+07,1.052835e+07,9.845692e+06,1.054023e+07,1.080614e+07,1.012157e+07
1,2025,United States of America,65_to_69,Male,Reference,Population,Number,9.439692e+06,8.612104e+06,1.003853e+07,...,9.557105e+06,9.760703e+06,1.023595e+07,9.194452e+06,8.998697e+06,9.438117e+06,8.832245e+06,9.451196e+06,9.690784e+06,9.076959e+06
2,2025,United States of America,65_to_69,Both,Reference,Population,Number,1.996994e+07,1.821429e+07,2.123490e+07,...,2.022031e+07,2.063840e+07,2.165829e+07,1.946290e+07,1.903184e+07,1.996647e+07,1.867794e+07,1.999142e+07,2.049692e+07,1.919853e+07
3,2025,United States of America,65_to_69,Female,BBBM Testing Only,Population,Number,1.053025e+07,9.602182e+06,1.119637e+07,...,1.066321e+07,1.087770e+07,1.142234e+07,1.026845e+07,1.003314e+07,1.052835e+07,9.845692e+06,1.054023e+07,1.080614e+07,1.012157e+07
4,2025,United States of America,65_to_69,Male,BBBM Testing Only,Population,Number,9.439692e+06,8.612104e+06,1.003853e+07,...,9.557105e+06,9.760703e+06,1.023595e+07,9.194452e+06,8.998697e+06,9.438117e+06,8.832245e+06,9.451196e+06,9.690784e+06,9.076959e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102595,2100,United Kingdom,65_plus,Male,BBBM Testing Only,Population,Number,8.211104e+06,7.812346e+06,8.586794e+06,...,8.155819e+06,8.163366e+06,8.298154e+06,8.198380e+06,8.184304e+06,8.097882e+06,7.963680e+06,8.143412e+06,7.909882e+06,8.554832e+06
102596,2100,United Kingdom,65_plus,Both,BBBM Testing Only,Population,Number,1.781940e+07,1.685420e+07,1.865542e+07,...,1.768271e+07,1.773710e+07,1.803271e+07,1.789857e+07,1.784744e+07,1.746192e+07,1.735553e+07,1.764959e+07,1.721110e+07,1.859581e+07
102597,2100,United Kingdom,65_plus,Female,BBBM Testing and Treatment,Population,Number,9.624290e+06,9.065585e+06,1.008647e+07,...,9.541777e+06,9.591930e+06,9.748152e+06,9.715561e+06,9.678139e+06,9.378973e+06,9.406334e+06,9.522937e+06,9.318131e+06,1.006098e+07
102598,2100,United Kingdom,65_plus,Male,BBBM Testing and Treatment,Population,Number,8.216580e+06,7.816583e+06,8.592453e+06,...,8.160491e+06,8.169314e+06,8.302163e+06,8.203563e+06,8.189536e+06,8.103463e+06,7.969092e+06,8.149951e+06,7.915511e+06,8.561145e+06
102599,2100,United Kingdom,65_plus,Both,BBBM Testing and Treatment,Population,Number,1.784087e+07,1.687014e+07,1.867892e+07,...,1.770227e+07,1.776124e+07,1.805031e+07,1.791912e+07,1.786767e+07,1.748244e+07,1.737543e+07,1.767289e+07,1.723364e+07,1.862212e+07

In [23]:
# Save population data
person_time_output.to_csv(output_dir / 'population.csv', index=False)

# Deaths and averted deaths

In [24]:
with Timer():
    results.load_measure_from_batch_runs('deaths', filters=loading.FINAL_RESULTS_FILTERS['deaths'])

print(len(results.data.deaths), 'rows')
results.data.deaths.head()

Timer BatchLoadingTimer started
[('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('entity', '==', 'alzheimers_disease_state')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('entity', '==', 'alzheimers_disease_state')]
421.355853 MB after read_parquet
2.559246 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('entity', '==', 'alzheimers_disease_state')]
421.355853 MB after read_parquet
2.559246 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch11/model_spec/2026_02_14_06_55_56/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('entity', '==', 'alzheimers_disease_state')]
421.355853 MB after read_parquet
2.559246 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch8/model_spec/2026_02_13_21_06_03/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('entity', '==', 'alzheimers_disease_state')]
421.355853 MB after read_parquet
2.559246 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch12/model_spec/2026_02_14_07_00_06/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('age_group', '!=', '25_to_29'), ('event_year', '>=', '2025'), ('entity', '==', 'alzheimers_disease_state')]
632.027853 MB after read_parquet
3.836046 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch1/model_spec/2026_02_13_12_41_14/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,value,location
0,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,deaths,baseline,Female,0.0,Japan
1,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,deaths,baseline,Male,0.0,Japan
2,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,deaths,bbbm_testing,Female,0.0,Japan
3,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,deaths,bbbm_testing,Male,0.0,Japan
4,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,deaths,bbbm_testing_and_treatment,Female,0.0,Japan

In [25]:
# Check that draws in the data match expected draws from the keyspace metadata
assert set(results.data.deaths.input_draw.unique()) == set(results.draws)

In [26]:
deaths_prepped = results.process_deaths(results.data.deaths)
deaths_prepped

44.693514 MB measure
14.901514 MB minuend
29.797514 MB subtrahend
9.585541 MB minuend re-indexed
19.161541 MB subtrahend re-indexed
19.161601 MB difference
34.053646 MB difference with reset index
35.117971 MB final difference

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,value,location,metric,disease_stage
0,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,Deaths Associated with AD,baseline,Female,0.0,Japan,Number,alzheimers_disease_state
1,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,Deaths Associated with AD,baseline,Male,0.0,Japan,Number,alzheimers_disease_state
2,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,Deaths Associated with AD,bbbm_testing,Female,0.0,Japan,Number,alzheimers_disease_state
3,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,Deaths Associated with AD,bbbm_testing,Male,0.0,Japan,Number,alzheimers_disease_state
4,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2025,35,Deaths Associated with AD,bbbm_testing_and_treatment,Female,0.0,Japan,Number,alzheimers_disease_state
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2659995,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2100,1,Averted Deaths Associated with AD,bbbm_testing_and_treatment,Male,-94.0,Brazil,Number,alzheimers_disease_state
2659996,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2100,211,Averted Deaths Associated with AD,bbbm_testing,Female,0.0,Brazil,Number,alzheimers_disease_state
2659997,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2100,211,Averted Deaths Associated with AD,bbbm_testing,Male,0.0,Brazil,Number,alzheimers_disease_state
2659998,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2100,211,Averted Deaths Associated with AD,bbbm_testing_and_treatment,Female,-430.0,Brazil,Number,alzheimers_disease_state
2659999,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_state,cause,2100,211,Averted Deaths Associated with AD,bbbm_testing_and_treatment,Male,-162.0,Brazil,Number,alzheimers_disease_state

In [27]:
deaths_prepped.query("0 < abs(value) < 1").value.describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: value, dtype: float64

In [28]:
# deaths_output = results.summarize_and_beautify(deaths_prepped, 'entity')
deaths_output = results.do_final_processing(deaths_prepped, include_draws=True)
deaths_output

2026-03-04 10:57:58.394028
Timer SummarizingTimer started
Elapsed time: 441.6310 seconds
2026-03-04 11:06:01.026138

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
0,2025,Brazil,65_to_69,Female,AD Dementia,Reference,Deaths Associated with AD,Number,2682.490014,2019.276367,...,2639.832595,2262.216282,2102.375233,1894.628069,2149.299302,2552.807762,2475.234518,2672.665043,2341.155717,2223.874097
1,2025,Brazil,65_to_69,Male,AD Dementia,Reference,Deaths Associated with AD,Number,1293.566515,961.454346,...,1415.703581,1266.903914,1108.552214,1055.662162,1316.295732,1353.050683,1466.924007,1277.592630,1352.994953,1268.692337
2,2025,Brazil,65_to_69,Both,AD Dementia,Reference,Deaths Associated with AD,Number,3976.056529,3106.672560,...,4055.536176,3529.120195,3210.927447,2950.290231,3465.595033,3905.858445,3942.158526,3950.257673,3694.150670,3492.566435
3,2025,Brazil,65_to_69,Female,AD Dementia,BBBM Testing Only,Deaths Associated with AD,Number,2682.490014,2019.276367,...,2639.832595,2262.216282,2102.375233,1894.628069,2149.299302,2552.807762,2475.234518,2672.665043,2341.155717,2223.874097
4,2025,Brazil,65_to_69,Male,AD Dementia,BBBM Testing Only,Deaths Associated with AD,Number,1293.566515,961.454346,...,1415.703581,1266.903914,1108.552214,1055.662162,1316.295732,1353.050683,1466.924007,1277.592630,1352.994953,1268.692337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341995,2100,United States of America,65_plus,Male,AD Dementia,BBBM Testing Only,Averted Deaths Associated with AD,Rate,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
341996,2100,United States of America,65_plus,Both,AD Dementia,BBBM Testing Only,Averted Deaths Associated with AD,Rate,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
341997,2100,United States of America,65_plus,Female,AD Dementia,BBBM Testing and Treatment,Averted Deaths Associated with AD,Rate,0.000149,0.000110,...,0.000124,0.000166,0.000121,0.000148,0.000142,0.000163,0.000156,0.000154,0.000165,0.000175
341998,2100,United States of America,65_plus,Male,AD Dementia,BBBM Testing and Treatment,Averted Deaths Associated with AD,Rate,0.000094,0.000064,...,0.000082,0.000099,0.000074,0.000081,0.000094,0.000100,0.000104,0.000120,0.000093,0.000104
341999,2100,United States of America,65_plus,Both,AD Dementia,BBBM Testing and Treatment,Averted Deaths Associated with AD,Rate,0.000124,0.000089,...,0.000105,0.000135,0.000100,0.000118,0.000120,0.000135,0.000132,0.000139,0.000132,0.000143

In [29]:
deaths_output.to_csv(output_dir / "deaths.csv", index=False)

# Prevalence

In [30]:
filename = 'person_time_alzheimers_disease_and_other_dementias'
prevalence_short_name = 'alzheimers_person_time'

# We should have loaded this when processing population above, but just
# in case we didn't, load it here
if prevalence_short_name not in results.data:
    with Timer():
        results.load_measure_from_batch_runs(filename, prevalence_short_name, filters=loading.FINAL_RESULTS_FILTERS[filename])

print(len(results.data[prevalence_short_name]), 'rows')
results.data[prevalence_short_name].head()

4788000 rows

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2025,35,person_time,baseline,Female,alzheimers_blood_based_biomarker_state,0.0,Japan
1,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2025,35,person_time,baseline,Female,alzheimers_mild_cognitive_impairment_state,0.0,Japan
2,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2025,35,person_time,baseline,Female,alzheimers_disease_state,0.0,Japan
3,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2025,35,person_time,baseline,Male,alzheimers_blood_based_biomarker_state,0.0,Japan
4,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2025,35,person_time,baseline,Male,alzheimers_mild_cognitive_impairment_state,0.0,Japan

In [31]:
results.data.alzheimers_person_time.query("age_group == '30_to_34' and value > 0")

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
72,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2027,35,person_time,baseline,Female,alzheimers_blood_based_biomarker_state,0.498289,Japan
78,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2027,35,person_time,bbbm_testing,Female,alzheimers_blood_based_biomarker_state,0.498289,Japan
84,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2027,35,person_time,bbbm_testing_and_treatment,Female,alzheimers_blood_based_biomarker_state,0.498289,Japan
108,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2028,35,person_time,baseline,Female,alzheimers_blood_based_biomarker_state,0.996578,Japan
114,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2028,35,person_time,bbbm_testing,Female,alzheimers_blood_based_biomarker_state,0.996578,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...
4431915,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2089,211,person_time,bbbm_testing,Male,alzheimers_blood_based_biomarker_state,0.996578,Brazil
4431921,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2089,211,person_time,bbbm_testing_and_treatment,Male,alzheimers_blood_based_biomarker_state,0.996578,Brazil
4432287,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2100,1,person_time,baseline,Male,alzheimers_blood_based_biomarker_state,1.993155,Brazil
4432293,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2100,1,person_time,bbbm_testing,Male,alzheimers_blood_based_biomarker_state,1.993155,Brazil
4432299,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2100,1,person_time,bbbm_testing_and_treatment,Male,alzheimers_blood_based_biomarker_state,1.993155,Brazil

In [32]:
processed_prevalence_short_name = f'{prevalence_short_name}_processed'

# We should have saved processed prevalence data when processing
# population above, but just in case we didn't, process it here
if processed_prevalence_short_name not in results.data:
    results.data[processed_prevalence_short_name] = results.process_prevalence_counts(results.data[prevalence_short_name])

prevalence_counts = results.data[processed_prevalence_short_name]
print_memory_usage(prevalence_counts)
print(len(prevalence_counts), 'rows')
prevalence_counts.tail()

159.609709 MB
7980000 rows

,age_group,artifact_path,entity,entity_type,event_year,input_draw,location,measure,scenario,sex,disease_stage,value,metric
7979995,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2100,249,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Female,alzheimers_mild_cognitive_impairment_state,3161.642710,Number
7979996,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2100,249,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Female,alzheimers_disease_state,4927.080082,Number
7979997,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2100,249,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Male,alzheimers_blood_based_biomarker_state,588.977413,Number
7979998,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2100,249,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Male,alzheimers_mild_cognitive_impairment_state,1173.470226,Number
7979999,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2100,249,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Male,alzheimers_disease_state,1665.281314,Number

In [35]:
prevalence_counts.query("value < 0")[['scenario', 'measure', 'disease_stage']].value_counts()

scenario                    measure                              disease_stage
bbbm_testing_and_treatment  Change in Prevalence from Reference  alzheimers_disease_state                      207244
                                                                 alzheimers_mild_cognitive_impairment_state    164551
dtype: int64

In [36]:
# Sometimes we increase the prevalence of MCI or dementia in some age groups
prevalence_counts.query(
    "measure == 'Change in Prevalence from Reference' and value > 0"
    " and disease_stage != 'alzheimers_blood_based_biomarker_state' "
    ).age_group.value_counts()

95_plus     55266
90_to_94    31030
85_to_89    14261
80_to_84        2
65_to_69        1
25_to_29        0
30_to_34        0
35_to_39        0
40_to_44        0
45_to_49        0
50_to_54        0
55_to_59        0
60_to_64        0
70_to_74        0
75_to_79        0
Name: age_group, dtype: int64

In [43]:
prevalence_counts.query(
    "measure == 'Change in Prevalence from Reference' and value > 0"
    " and disease_stage != 'alzheimers_blood_based_biomarker_state'"
    " and age_group in ['65_to_69', '80_to_84']"
    )

,age_group,artifact_path,entity,entity_type,event_year,input_draw,location,measure,scenario,sex,disease_stage,value,metric
6476866,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2030,172,United Kingdom,Change in Prevalence from Reference,bbbm_testing_and_treatment,Male,alzheimers_mild_cognitive_impairment_state,0.498289,Number
7160972,80_to_84,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2030,245,United Kingdom,Change in Prevalence from Reference,bbbm_testing_and_treatment,Female,alzheimers_disease_state,0.498289,Number
7183772,80_to_84,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2030,245,United States of America,Change in Prevalence from Reference,bbbm_testing_and_treatment,Female,alzheimers_disease_state,0.498289,Number

In [37]:
prevalence_counts.query("0 < abs(value) < 1")

,age_group,artifact_path,entity,entity_type,event_year,input_draw,location,measure,scenario,sex,disease_stage,value,metric
37,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2025,7,Japan,Prevalence,baseline,Female,alzheimers_mild_cognitive_impairment_state,0.996578,Number
43,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2025,7,Japan,Prevalence,bbbm_testing,Female,alzheimers_mild_cognitive_impairment_state,0.996578,Number
49,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2025,7,Japan,Prevalence,bbbm_testing_and_treatment,Female,alzheimers_mild_cognitive_impairment_state,0.996578,Number
487,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2026,7,Japan,Prevalence,baseline,Female,alzheimers_mild_cognitive_impairment_state,0.498289,Number
493,30_to_34,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2026,7,Japan,Prevalence,bbbm_testing,Female,alzheimers_mild_cognitive_impairment_state,0.498289,Number
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7964591,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2049,187,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Male,alzheimers_disease_state,0.996578,Number
7964675,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2049,245,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Male,alzheimers_disease_state,-0.996578,Number
7964747,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2050,24,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Male,alzheimers_disease_state,-0.996578,Number
7964867,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2050,172,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Male,alzheimers_disease_state,0.996578,Number
7965008,95_plus,/mnt/team/simulation_science/pub/models/vivari...,alzheimers_disease_and_other_dementias,cause,2051,1,Brazil,Change in Prevalence from Reference,bbbm_testing_and_treatment,Female,alzheimers_disease_state,0.498289,Number

In [38]:
prevalence_counts.query("abs(value) >= 1e-9")['value'].describe() # count 4.940696e+06

count    4.940696e+06
mean     5.203500e+04
std      8.136165e+04
min     -2.407433e+04
25%      1.614456e+03
50%      1.313489e+04
75%      6.950781e+04
max      6.399339e+05
Name: value, dtype: float64

In [39]:
results.data.keys()

dict_keys(['ops', 'alzheimers_person_time', 'alzheimers_person_time_processed', 'deaths'])

In [40]:
with Timer():
    # prevalence_output = results.summarize_and_beautify(prevalence_counts)
    prevalence_output = results.do_final_processing(prevalence_counts, include_draws=True)
print_memory_usage(prevalence_output)
print(len(prevalence_output), 'rows')
prevalence_output.tail()

2026-03-04 11:06:12.298056
Timer SummarizingTimer started

Elapsed time: 1328.9675 seconds
2026-03-04 11:29:52.646397
Elapsed time: 0:23:40.348550
238.038787 MB
1026000 rows

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,...,draw_187,draw_199,draw_204,draw_211,draw_219,draw_235,draw_236,draw_245,draw_248,draw_249
1025995,2100,United States of America,65_plus,Male,AD Dementia,BBBM Testing Only,Change in Prevalence from Reference,Rate,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1025996,2100,United States of America,65_plus,Both,AD Dementia,BBBM Testing Only,Change in Prevalence from Reference,Rate,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1025997,2100,United States of America,65_plus,Female,AD Dementia,BBBM Testing and Treatment,Change in Prevalence from Reference,Rate,-0.002032,-0.002615,...,-0.001820,-0.002201,-0.001607,-0.001976,-0.001960,-0.002375,-0.002258,-0.002207,-0.002399,-0.002555
1025998,2100,United States of America,65_plus,Male,AD Dementia,BBBM Testing and Treatment,Change in Prevalence from Reference,Rate,-0.001124,-0.001421,...,-0.000983,-0.001203,-0.000882,-0.001043,-0.001153,-0.001163,-0.001231,-0.001356,-0.001163,-0.001236
1025999,2100,United States of America,65_plus,Both,AD Dementia,BBBM Testing and Treatment,Change in Prevalence from Reference,Rate,-0.001621,-0.002074,...,-0.001442,-0.001744,-0.001281,-0.001557,-0.001593,-0.001826,-0.001795,-0.001822,-0.001836,-0.001957

In [41]:
# Save prevalence data
prevalence_output.to_csv(output_dir / 'prevalence.csv', index=False)

In [42]:
!date

Wed Mar  4 11:30:22 PST 2026