In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
import numpy as np, os
import matplotlib.pyplot as plt

from pathlib import Path
# import yaml
# import re
# import datetime

# import pyarrow as pa
# import pyarrow.parquet as pq

# import gbd_mapping as gm
# from vivarium import Artifact

# from db_queries import get_ids, get_outputs, get_population, get_covariate_estimates
# from get_draws.api import get_draws

import vivarium_helpers as vh
# import vivarium_helpers.id_helper as idh
# from vivarium_helpers.vph_output.operations import VPHOperator
# from vivarium_helpers.vph_output.measures import VPHResults
from vivarium_helpers.utils import convert_to_categorical, constant_categorical, print_memory_usage, Timer
# from vivarium_helpers.vph_output import cleaning
# from vivarium_helpers.vph_output.loading import load_draws_from_keyspace_files
from vivarium_helpers.projects.alzheimers import loading, population
from vivarium_helpers.projects.alzheimers.population import RunType
# from vivarium_helpers.vph_artifact.operations import convert_to_sim_format
from vivarium_helpers.projects.alzheimers.results import AlzheimersResultsProcessor

!date
!whoami
!uname -a
!pwd

Fri Feb 20 20:18:58 PST 2026
ndbs
Linux long-slurm-sarchive-p0061 5.4.0-216-generic #236-Ubuntu SMP Fri Apr 11 19:53:21 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
/mnt/share/code/ndbs/vivarium_research_alzheimers/results_tables

In [4]:
# from vivarium_helpers.projects.alzheimers.results import AlzheimersResultsProcessor

# Record version of Vivarium Helpers

In [5]:
!conda list | grep vivarium

# packages in environment at /ihme/homes/ndbs/miniconda3/envs/vivarium_csu_alzheimers_artifact:
vivarium                  3.4.12                   pypi_0    pypi
vivarium-build-utils      2.0.4                    pypi_0    pypi
vivarium-cluster-tools    2.1.17                   pypi_0    pypi
vivarium-csu-alzheimers   0.1.dev18+g43e997c.d20250808          pypi_0    pypi
vivarium-dependencies     1.0.1                    pypi_0    pypi
vivarium-gbd-access       4.2.4                    pypi_0    pypi
vivarium-helpers          0.2.0                     dev_0    <develop>
vivarium-inputs           6.0.4                    pypi_0    pypi
vivarium-public-health    4.3.5                    pypi_0    pypi

In [6]:
!pip freeze | grep vivarium

vivarium==3.4.12
vivarium_build_utils==2.0.4
vivarium_cluster_tools==2.1.17
-e git+https://github.com/ihmeuw/vivarium_csu_alzheimers.git@263eb3d9b80b13735a7380bb892430eaba92603a#egg=vivarium_csu_alzheimers
vivarium_dependencies==1.0.1
vivarium_gbd_access==4.2.4
-e git+https://github.com/ihmeuw/vivarium_helpers.git@09402927b9a7f23694e85e33842e70334d91a474#egg=vivarium_helpers
vivarium_inputs==6.0.4
vivarium_public_health==4.3.5

# Define data directories

In [7]:
# Project directory
project_dir = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/')

# Output directory to store final results for client
output_dir = Path(r"J:\Project\simulation_science\alzheimers\results_in_progress".replace('\\', '/').replace('J:', '/snfs1'))
print(output_dir.exists())

# Output from multistate life table
# mslt_output_dir = output_dir.parent / 'results_12_4_2025_mslt'
mslt_output_dir = project_dir / 'results' / 'mslt_draws'
print(mslt_output_dir.exists())
output_dir

True
True

PosixPath('/snfs1/Project/simulation_science/alzheimers/results_in_progress')

In [8]:
# # For testing: Run directory containing model 8.3 results for all
# # locations
# model_run_subdir = 'results/abie_consistent_model_test/united_states_of_america/2025_10_28_08_55_05/'

# # Results directory for model 8.3, for testing
# results_dirs = project_dir / model_run_subdir / 'results/'

# Artifact for models 10.0 - 12.2
artifact_model_number = '10.0'

In [9]:
# Model 8.4 results (final runs for 10/31/25 intermediate results)
# Each batch run contains all locations, 100 random seeds, and 3 or 4 draws
model_run_dir_8_4 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model8.4/model_spec')

# Model 8.7 results (updated final run completed on 11/10/2025)
model_run_dir_8_7 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model8.7/model_spec')

# Model 12.2 results (updated final run completed on 02/14/2026)
model_run_dir_12_2 = Path('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2')

# Batch runs are stored in "timestamp" subdirectories of the model run
# directory.
# In model 12.2, the run directories are nested under two more levels of
# subfolders: batch number, then model_spec, then timestamp.

# Select a model and filter for testing
batch_run_dirs = loading.list_batch_run_directories(model_run_dir_12_2)[:2]

# batch_results_dirs
batch_run_dirs

['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25',
 '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15']

# Create an AlzheimersResultsProcessor object to process results

In [10]:
results = AlzheimersResultsProcessor('10.0', RunType.FINAL, batch_run_dirs=batch_run_dirs)

In [11]:
results.initial_simulation_population

2000000

In [12]:
results.locations

['United States of America',
 'Brazil',
 'China',
 'Germany',
 'Israel',
 'Japan',
 'Spain',
 'Sweden',
 'Taiwan (Province of China)',
 'United Kingdom']

In [13]:
results.draws

[35, 187, 41, 123]

# Load population data and calculate model scale

In [14]:
with Timer():
    results.load_population_data(append_aggregates=True)
results.ops.describe(results.model_scale)

Elapsed time: 0:00:21.027057

,count,mean,std,min,25%,50%,75%,max
location,,,,,,,,
Brazil,4.0,0.642785,0.040128,0.615948,0.617703,0.626814,0.651896,0.701564
China,4.0,0.073118,0.006218,0.067459,0.068853,0.071823,0.076088,0.081367
Germany,4.0,0.565683,0.021516,0.546277,0.550903,0.561059,0.575839,0.594337
Israel,4.0,27.126830,3.231229,24.092479,24.474834,27.063473,29.715468,30.287894
Japan,4.0,0.350457,0.014043,0.335773,0.341150,0.349226,0.358534,0.367604
Spain,4.0,1.844920,0.026759,1.814254,1.828701,1.844825,1.861044,1.875775
Sweden,4.0,7.646288,0.435738,7.066242,7.455519,7.721332,7.912100,8.076247
Taiwan (Province of China),4.0,5.330486,0.352312,4.818399,5.265450,5.441677,5.506713,5.620192
United Kingdom,4.0,1.201244,0.031209,1.167644,1.179329,1.201019,1.222934,1.235296
United States of America,4.0,0.267141,0.007819,0.261328,0.263282,0.264280,0.268138,0.278674

In [15]:
results.person_time

,location,sex,event_year,input_draw,value,age_group
0,United States of America,Female,2025,35,1.097634e+07,65_to_69
1,United States of America,Female,2025,187,1.066321e+07,65_to_69
2,United States of America,Female,2025,41,1.063578e+07,65_to_69
3,United States of America,Female,2025,123,1.104572e+07,65_to_69
4,United States of America,Female,2026,35,1.106931e+07,65_to_69
...,...,...,...,...,...,...
145915,Spain,Both,2100,187,1.585391e+07,65_plus
145916,Sweden,Both,2100,187,3.084375e+06,65_plus
145917,Taiwan (Province of China),Both,2100,187,6.968960e+06,65_plus
145918,United Kingdom,Both,2100,187,1.768271e+07,65_plus
145919,United States of America,Both,2100,187,7.948352e+07,65_plus

In [16]:
results.person_time.input_draw.unique()

array([ 35, 187,  41, 123], dtype=int16)

In [17]:
results.person_time.age_group.unique()

['65_to_69', '70_to_74', '75_to_79', '80_to_84', '85_to_89', ..., '45_to_49', '50_to_54', '55_to_59', '60_to_64', '65_plus']
Length: 16
Categories (16, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '85_to_89' < '90_to_94' < '95_plus' < '65_plus']

# Load and process deaths data for testing

In [18]:
# with Timer():
#     results.load_measure_from_batch_runs('deaths', filters=loading.FINAL_RESULTS_FILTERS['deaths'])

In [19]:
# results.data.deaths

In [20]:
# deaths_prepped = results.process_deaths(results.data.deaths)
# deaths_prepped

# Preprocess MSLT results

In [21]:
!ls $mslt_output_dir

v4_2026_01_14_outside_sim_results_draw_level.csv
v4_2026_02_03_outside_sim_results_draw_level.csv
v4_2026_02_18_outside_sim_results_draw_level.csv

In [22]:
mslt_results = pd.read_csv(mslt_output_dir / 'v4_2026_02_18_outside_sim_results_draw_level.csv', index_col=0)
mslt_results

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Draw,Value
0,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_1,0.000000
1,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_103,0.000000
2,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_122,0.000000
3,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_123,0.000000
4,2025,Brazil,65_to_69,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_161,0.000000
...,...,...,...,...,...,...,...,...,...,...
113995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_50,2015.073423
113996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_6,1966.509895
113997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_63,2025.659827
113998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_69,2127.428568
113999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_7,2046.368615

In [23]:
mslt_results.Age.unique()

array(['65_to_69', '70_to_74', '75_to_79'], dtype=object)

In [24]:
mslt_results.Draw.unique()

array(['draw_1', 'draw_103', 'draw_122', 'draw_123', 'draw_161',
       'draw_172', 'draw_183', 'draw_187', 'draw_199', 'draw_204',
       'draw_211', 'draw_219', 'draw_235', 'draw_236', 'draw_24',
       'draw_245', 'draw_248', 'draw_249', 'draw_35', 'draw_41',
       'draw_50', 'draw_6', 'draw_63', 'draw_69', 'draw_7'], dtype=object)

In [25]:
mslt_results.Scenario.unique()

array(['BBBM Testing Only', 'BBBM Testing and Treatment'], dtype=object)

In [26]:
mslt_results_prepped = results.process_mslt_results(mslt_results)
mslt_results_prepped

,input_draw,location,age_group,disease_stage,event_year,measure,metric,scenario,sex,value
0,35,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
1,35,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
2,35,Brazil,75_to_79,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
3,35,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Male,0.000000
4,35,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Male,0.000000
...,...,...,...,...,...,...,...,...,...,...
109435,187,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,618.415446
109436,187,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,598.598350
109437,187,United States of America,65_to_69,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,762.779941
109438,187,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,574.782529
109439,187,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,556.363648

In [27]:
mslt_results_prepped.measure.unique()

['BBBM Tests', 'Positive BBBM Tests', 'Medication Initiation']
Categories (3, object): ['BBBM Tests', 'Medication Initiation', 'Positive BBBM Tests']

# BBBM Test Counts

In [28]:
filename = 'counts_bbbm_tests'
# short_name = 'bbbm_tests'
with Timer():
    bbbm_tests = results.load_measure_from_batch_runs(
        filename, False, filters=loading.FINAL_RESULTS_FILTERS[filename])

bbbm_tests

Timer BatchLoadingTimer started
[('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('bbbm_test_results', '!=', 'not_tested'), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '!=', 'baseline')]
124.043997 MB after read_parquet
0.808608 MB after aggregating seeds and converting dtypes
1.611168 MB total
1.611168 MB after enforcing dtypes
Elapsed time: 4.3171 seconds
Elapsed time: 0:00:04.317552

,age_group,artifact_path,bbbm_test_results,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing,Female,,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing,Male,,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing_and_treatment,Female,,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,35,counts_bbbm_tests,bbbm_testing_and_treatment,Male,,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,positive,bbbm_testing,testing,2025,187,counts_bbbm_tests,bbbm_testing,Female,,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72955,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,41,counts_bbbm_tests,bbbm_testing_and_treatment,Male,,11346.0,China
72956,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,123,counts_bbbm_tests,bbbm_testing,Female,,18962.0,China
72957,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,123,counts_bbbm_tests,bbbm_testing,Male,,19837.0,China
72958,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,123,counts_bbbm_tests,bbbm_testing_and_treatment,Female,,18962.0,China
72959,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,negative,bbbm_testing,testing,2100,123,counts_bbbm_tests,bbbm_testing_and_treatment,Male,,19837.0,China

In [29]:
bbbm_tests.age_group.unique()

['65_to_69', '70_to_74', '75_to_79']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [30]:
bbbm_tests.query("value>0").age_group.unique()

['65_to_69', '70_to_74', '75_to_79']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [31]:
bbbm_tests.bbbm_test_results.unique()

['positive', 'negative']
Categories (3, object): ['negative', 'not_tested', 'positive']

In [32]:
bbbm_tests.query("value>0").scenario.unique()

['bbbm_testing', 'bbbm_testing_and_treatment']
Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [33]:
bbbm_tests_prepped = results.process_bbbm_tests(bbbm_tests, mslt_results_prepped)
bbbm_tests_prepped

,age_group,event_year,input_draw,location,measure,scenario,sex,value,disease_stage,metric
0,65_to_69,2025,35,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
1,65_to_69,2025,35,Japan,BBBM Tests,bbbm_testing,Male,0.000000,Preclinical AD,Number
2,65_to_69,2025,35,Japan,BBBM Tests,bbbm_testing_and_treatment,Female,0.000000,Preclinical AD,Number
3,65_to_69,2025,35,Japan,BBBM Tests,bbbm_testing_and_treatment,Male,0.000000,Preclinical AD,Number
4,65_to_69,2025,41,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
...,...,...,...,...,...,...,...,...,...,...
145915,70_to_74,2100,187,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Female,780.409549,Susceptible,Number
145916,75_to_79,2100,187,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Female,755.401359,Susceptible,Number
145917,65_to_69,2100,187,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,962.590365,Susceptible,Number
145918,70_to_74,2100,187,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,725.346977,Susceptible,Number
145919,75_to_79,2100,187,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,702.103265,Susceptible,Number

In [34]:
bbbm_tests_prepped.disease_stage.unique()

['Preclinical AD', 'Susceptible']
Categories (2, object): ['Preclinical AD', 'Susceptible']

In [35]:
bbbm_tests_prepped.measure.unique()

['BBBM Tests', 'Positive BBBM Tests']
Categories (2, object): ['BBBM Tests', 'Positive BBBM Tests']

In [36]:
with Timer():
    bbbm_tests_output = results.summarize_and_beautify(bbbm_tests_prepped, 'disease_stage')
bbbm_tests_output
# 121600 rows

Timer SummarizingTimer started
2026-02-20 20:19:36.406048
2026-02-20 20:19:38.342474
2026-02-20 20:22:52.920804
Elapsed time: 196.5245 seconds
Elapsed time: 0:03:16.524943

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
145915,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000250,0.000249,0.000251
145916,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000237,0.000236,0.000237
145917,2100,United States of America,65_plus,Female,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000226,0.000223,0.000228
145918,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000250,0.000249,0.000251
145919,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000237,0.000236,0.000237

In [37]:
bbbm_tests_output.Measure.unique()

['BBBM Tests', 'Positive BBBM Tests']
Categories (2, object): ['BBBM Tests', 'Positive BBBM Tests']

In [38]:
bbbm_tests_output.Age.unique()

['65_to_69', '70_to_74', '75_to_79', '65_plus']
Categories (4, object): ['65_plus', '65_to_69', '70_to_74', '75_to_79']

In [39]:
bbbm_tests_output.query("Mean>0").Scenario.unique()

['BBBM Testing Only', 'BBBM Testing and Treatment']
Categories (2, object): ['BBBM Testing Only', 'BBBM Testing and Treatment']

In [40]:
bbbm_tests_output.query(
    "Year == 2100 & Location == 'United States of America' & Age == '75_to_79' & Sex == 'Male' & `Disease Stage` == 'Susceptible' & Scenario == 'BBBM Testing Only' & Measure == 'Positive BBBM Tests'"
)

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
109429,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Number,2672.261957,2603.947928,2738.074053
109435,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000395,0.000392,0.000398

In [41]:
temp = results.do_final_processing(bbbm_tests_prepped)
temp

2026-02-20 20:38:43.130834
Timer SummarizingTimer started
Elapsed time: 875.3218 seconds
2026-02-20 20:53:20.394664

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_plus,Both,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
1,2025,Brazil,65_plus,Female,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
2,2025,Brazil,65_plus,Male,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
3,2025,Brazil,65_plus,Both,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000
4,2025,Brazil,65_plus,Female,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
145915,2100,United States of America,75_to_79,Female,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000367,0.000363,0.000370
145916,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000395,0.000392,0.000398
145917,2100,United States of America,75_to_79,Both,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000380,0.000379,0.000381
145918,2100,United States of America,75_to_79,Female,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000367,0.000363,0.000370
145919,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000395,0.000392,0.000398

In [45]:
results.ops.assert_values_equal(temp, bbbm_tests_output, value_cols=['Mean', '95% UI Lower', '95% UI Upper'], check_exact=False)

In [46]:
temp2 = results.do_final_processing(bbbm_tests_prepped, include_draws=False)
temp2

2026-02-20 21:10:26.304957
Timer SummarizingTimer started
Elapsed time: 178.2544 seconds
2026-02-20 21:13:26.622666

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
145915,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000250,0.000249,0.000251
145916,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000237,0.000236,0.000237
145917,2100,United States of America,65_plus,Female,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000226,0.000223,0.000228
145918,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000250,0.000249,0.000251
145919,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000237,0.000236,0.000237

In [47]:
results.ops.assert_values_equal(temp2, bbbm_tests_output, value_cols=['Mean', '95% UI Lower', '95% UI Upper'], check_exact=False)

In [48]:
temp3 = results.do_final_processing(bbbm_tests_prepped, include_draws=True)
temp3

2026-02-20 21:17:47.727822
Timer SummarizingTimer started
Elapsed time: 177.8118 seconds
2026-02-20 21:20:47.200678

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper,draw_35,draw_41,draw_123,draw_187
0,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2025,Brazil,65_to_69,Both,Preclinical AD,BBBM Testing Only,BBBM Tests,Number,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2025,Brazil,65_to_69,Female,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2025,Brazil,65_to_69,Male,Preclinical AD,BBBM Testing and Treatment,BBBM Tests,Number,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145915,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000250,0.000249,0.000251,0.000249,0.000249,0.000251,0.000251
145916,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing Only,Positive BBBM Tests,Rate,0.000237,0.000236,0.000237,0.000237,0.000237,0.000237,0.000236
145917,2100,United States of America,65_plus,Female,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000226,0.000223,0.000228,0.000228,0.000227,0.000227,0.000223
145918,2100,United States of America,65_plus,Male,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000250,0.000249,0.000251,0.000249,0.000249,0.000251,0.000251
145919,2100,United States of America,65_plus,Both,Susceptible,BBBM Testing and Treatment,Positive BBBM Tests,Rate,0.000237,0.000236,0.000237,0.000237,0.000237,0.000237,0.000236

In [38]:
# Save BBBM testing results
bbbm_tests_output.to_csv(output_dir / 'bbbm_tests.csv', index=False)

# CSF and PET Test Counts

In [39]:
# csf_pet_filters = [('testing_state', 'in', ['csf', 'pet'])]
filename = 'counts_baseline_tests_among_eligible'
with Timer():
    csf_pet_tests = results.load_measure_from_batch_runs(
        filename, False, filters=loading.FINAL_RESULTS_FILTERS[filename]
    )
print(len(csf_pet_tests), 'rows')
csf_pet_tests.head()

Timer BatchLoadingTimer started
[('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
930.252135 MB after read_parquet

6.025386 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('testing_state', 'in', ['csf', 'pet'])]
930.252135 MB after read_parquet
6.025386 MB after aggregating seeds and converting dtypes
12.044586 MB total
12.044586 MB after enforcing dtypes
Elapsed time: 22.1591 seconds
Elapsed time: 0:00:22.159607
547200 rows

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,testing_state,value,location
0,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Female,,csf,0.0,Japan
1,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Female,,pet,0.0,Japan
2,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Male,,csf,0.0,Japan
3,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,baseline,Male,,pet,0.0,Japan
4,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,counts_baseline_tests_among_eligible,bbbm_testing,Female,,csf,0.0,Japan

In [40]:
csf_pet_tests.query("value>0").age_group.unique()

['30_to_34', '35_to_39', '40_to_44', '45_to_49', '50_to_54', ..., '75_to_79', '80_to_84', '85_to_89', '90_to_94', '95_plus']
Length: 14
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [41]:
csf_pet_tests_prepped = results.process_csf_pet_tests(csf_pet_tests)
csf_pet_tests_prepped

16.422297 MB measure
5.478297 MB minuend
10.950297 MB subtrahend
3.6579 MB minuend re-indexed
7.3059 MB subtrahend re-indexed
7.30596 MB difference
12.409629 MB difference with reset index
12.774754 MB final difference

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,testing_state,value,location,metric,disease_stage
0,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,CSF Tests,baseline,Female,,csf,0.0,Japan,Number,MCI due to AD
1,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,PET Tests,baseline,Female,,pet,0.0,Japan,Number,MCI due to AD
2,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,CSF Tests,baseline,Male,,csf,0.0,Japan,Number,MCI due to AD
3,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,PET Tests,baseline,Male,,pet,0.0,Japan,Number,MCI due to AD
4,25_to_29,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2025,35,CSF Tests,bbbm_testing,Female,,csf,0.0,Japan,Number,MCI due to AD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911995,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,123,Averted PET Tests,bbbm_testing,Male,,pet,0.0,China,Number,MCI due to AD
911996,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,123,Averted CSF Tests,bbbm_testing_and_treatment,Female,,csf,10.0,China,Number,MCI due to AD
911997,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,123,Averted PET Tests,bbbm_testing_and_treatment,Female,,pet,2.0,China,Number,MCI due to AD
911998,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,123,Averted CSF Tests,bbbm_testing_and_treatment,Male,,csf,1.0,China,Number,MCI due to AD
911999,95_plus,/mnt/team/simulation_science/pub/models/vivari...,baseline_testing,testing,2100,123,Averted PET Tests,bbbm_testing_and_treatment,Male,,pet,0.0,China,Number,MCI due to AD

In [41]:
csf_pet_tests_output = results.summarize_and_beautify(csf_pet_tests_prepped, 'disease_stage')
csf_pet_tests_output

Timer SummarizingTimer started
2026-02-18 15:44:35.175278
2026-02-18 15:44:41.773891
2026-02-18 15:55:22.312000
Elapsed time: 647.1682 seconds

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_to_69,Female,MCI due to AD,Reference,CSF Tests,Number,3636.585776,2565.971066,5149.071612
1,2025,Brazil,65_to_69,Male,MCI due to AD,Reference,CSF Tests,Number,1463.545083,914.718407,1953.218211
2,2025,Brazil,65_to_69,Both,MCI due to AD,Reference,CSF Tests,Number,5100.130860,3495.101727,7087.877569
3,2025,Brazil,65_to_69,Female,MCI due to AD,BBBM Testing Only,CSF Tests,Number,3636.585776,2565.971066,5149.071612
4,2025,Brazil,65_to_69,Male,MCI due to AD,BBBM Testing Only,CSF Tests,Number,1463.545083,914.718407,1953.218211
...,...,...,...,...,...,...,...,...,...,...,...
729595,2100,United States of America,65_plus,Male,MCI due to AD,BBBM Testing Only,Averted PET Tests,Rate,0.000328,0.000128,0.000442
729596,2100,United States of America,65_plus,Both,MCI due to AD,BBBM Testing Only,Averted PET Tests,Rate,0.000451,0.000165,0.000638
729597,2100,United States of America,65_plus,Female,MCI due to AD,BBBM Testing and Treatment,Averted PET Tests,Rate,0.000552,0.000197,0.000799
729598,2100,United States of America,65_plus,Male,MCI due to AD,BBBM Testing and Treatment,Averted PET Tests,Rate,0.000328,0.000128,0.000442
729599,2100,United States of America,65_plus,Both,MCI due to AD,BBBM Testing and Treatment,Averted PET Tests,Rate,0.000451,0.000165,0.000638

In [42]:
# Save CSF/PET testing results
csf_pet_tests_output.to_csv(output_dir / 'csf_pet_tests.csv', index=False)

In [43]:
assert False, "Stop here for now"

AssertionError: Stop here for now

# Treatment Counts

We count treatments using treatment transition counts in older models, and with the treatment duration counts starting in model 11.0

In [45]:
# treatments_filters = [
#     ('sub_entity', 'in',
#      ['susceptible_to_treatment_to_waiting_for_treatment',
#       'waiting_for_treatment_to_full_effect_long',
#       'waiting_for_treatment_to_full_effect_short']
#     )
# ]
treatment_transitions_filename = 'transition_count_treatment'

with Timer():
    treatment_transitions = results.load_measure_from_batch_runs(
        treatment_transitions_filename, False, 
        filters=loading.FINAL_RESULTS_FILTERS[treatment_transitions_filename]
    )
print(len(treatment_transitions), 'rows')
treatment_transitions.head()

Timer BatchLoadingTimer started
[('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84'])]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84'])]
120.396194 MB after read_parquet
0.772325 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', 'in', ['waiting_for_treatment_to_full_effect_long', 'waiting_for_treatment_to_full_effect_short', 'waiting_for_treatment_to_treatment_effect']), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79', '80_to_84'])]
120.396194 MB after read_parquet
0.772325 MB after aggregating seeds and converting dtypes
1.538405 MB total
1.538405 MB after enforcing dtypes
Elapsed time: 4.6144 seconds
Elapsed time: 0:00:04.614664
72960 rows

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,transition_count,baseline,Female,waiting_for_treatment_to_treatment_effect,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,transition_count,baseline,Male,waiting_for_treatment_to_treatment_effect,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,transition_count,bbbm_testing,Female,waiting_for_treatment_to_treatment_effect,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,transition_count,bbbm_testing,Male,waiting_for_treatment_to_treatment_effect,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,transition_count,bbbm_testing_and_treatment,Female,waiting_for_treatment_to_treatment_effect,0.0,Japan

In [46]:
treatment_transitions.sub_entity.unique()

['waiting_for_treatment_to_treatment_effect']
Categories (5, object): ['susceptible_to_treatment_to_no_effect_never_t..., 'susceptible_to_treatment_to_waiting_for_treat..., 'treatment_effect_to_waning_effect', 'waiting_for_treatment_to_treatment_effect', 'waning_effect_to_no_effect_after_treatment']

In [58]:
treatment_transitions.query("value>0").scenario.unique()

['bbbm_testing_and_treatment']
Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [62]:
treatment_months_filename = 'treatment_duration'
# treatment_months_filters = [
#     ('sub_entity', '!=', 0),
#     ('age_group', 'in', loading.TESTING_ELIGIBLE_AGE_GROUPS),
#     # ('scenario', '==', 'bbbm_testing_and_treatment'),
# ] 

with Timer():
    treatment_months = results.load_measure_from_batch_runs(
        treatment_months_filename, False,
        filters=loading.FINAL_RESULTS_FILTERS[treatment_months_filename]
    )
print(len(treatment_months), 'rows')
treatment_months.head()

Timer BatchLoadingTimer started
[('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch5/model_spec/2026_02_13_17_56_25/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
{'all': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/model12.2/batch9/model_spec/2026_02_14_06_54_15/results')}
{'United States of America': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', 'Brazil': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', 'China': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', 'Germany': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', 'Israel': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', 'Japan': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', 'Spain': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', 'Sweden': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', 'Taiwan (Province of China)': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', 'United Kingdom': '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'}
('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf'])
[('artifact_path', 'in', ['/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_states_of_america.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/brazil.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/china.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/germany.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/israel.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/japan.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/spain.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/sweden.hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/taiwan_(province_of_china).hdf', '/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/artifacts/model10.0/united_kingdom.hdf']), ('event_year', '>=', '2025'), ('sub_entity', '!=', 0), ('age_group', 'in', ['65_to_69', '70_to_74', '75_to_79']), ('scenario', '==', 'bbbm_testing_and_treatment')]
328.331529 MB after read_parquet
1.729632 MB after aggregating seeds and converting dtypes
3.453312 MB total
3.453312 MB after enforcing dtypes
Elapsed time: 63.7040 seconds
Elapsed time: 0:01:03.706728
164160 rows

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan

In [63]:
treatment_months.query("value>0").sub_entity.unique()

[1, 6, 9, 7, 3, 4, 8, 2, 5]
Categories (9, int64): [1, 2, 3, 4, ..., 6, 7, 8, 9]

In [64]:
treatment_months.query("value>0").scenario.unique()

['bbbm_testing_and_treatment']
Categories (3, object): ['baseline' < 'bbbm_testing' < 'bbbm_testing_and_treatment']

In [65]:
start_treatment = [
        'waiting_for_treatment_to_full_effect_long',
        'waiting_for_treatment_to_full_effect_short',
        'waiting_for_treatment_to_treatment_effect']
treatment_transitions.query("sub_entity in @start_treatment and value>0").age_group.unique()

['65_to_69', '70_to_74', '75_to_79', '80_to_84']
Categories (15, object): ['25_to_29' < '30_to_34' < '35_to_39' < '40_to_44' ... '80_to_84' < '85_to_89' < '90_to_94' < '95_plus']

In [66]:
# # Now empty because we filter out this transition on loading
# treatments.query("sub_entity=='susceptible_to_treatment_to_waiting_for_treatment' and value>0").age_group.unique()
# # Should be ['60_to_64', '65_to_69', '70_to_74', '75_to_79']

In [67]:
# Check which transitions are present in the treatment transitions
# dataframe, to determine whether we should use treatment transition
# counts or treatment duration counts to count completed vs.
# discontinued treatments
unique_transitions = treatment_transitions['sub_entity'].unique()

if ('waiting_for_treatment_to_full_effect_long' in unique_transitions
    and 'waiting_for_treatment_to_full_effect_short' in unique_transitions):
    treatments = treatment_transitions
elif 'waiting_for_treatment_to_treatment_effect' in unique_transitions:
    treatments = treatment_months
else:
    raise ValueError(
        f"Missing expected treatment transitions: {unique_transitions}")

treatments

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...
164155,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,5,194.0,China
164156,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,6,188.0,China
164157,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,7,225.0,China
164158,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,8,188.0,China
164159,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,9,14545.0,China

In [100]:
treatments_prepped = results.process_treatments(treatments, mslt_results_prepped)
treatments_prepped

,age_group,event_year,input_draw,location,scenario,sex,measure,value,disease_stage
0,65_to_69,2025,35,Japan,bbbm_testing_and_treatment,Female,Medication Discontinuation,0.000000,Preclinical AD
1,65_to_69,2025,35,Japan,bbbm_testing_and_treatment,Female,Medication Completion,0.000000,Preclinical AD
2,65_to_69,2025,35,Japan,bbbm_testing_and_treatment,Male,Medication Discontinuation,0.000000,Preclinical AD
3,65_to_69,2025,35,Japan,bbbm_testing_and_treatment,Male,Medication Completion,0.000000,Preclinical AD
4,65_to_69,2025,41,Japan,bbbm_testing_and_treatment,Female,Medication Discontinuation,0.000000,Preclinical AD
...,...,...,...,...,...,...,...,...,...
72955,70_to_74,2100,187,United States of America,BBBM Testing and Treatment,Female,Medication Initiation,618.415446,Susceptible
72956,75_to_79,2100,187,United States of America,BBBM Testing and Treatment,Female,Medication Initiation,598.598350,Susceptible
72957,65_to_69,2100,187,United States of America,BBBM Testing and Treatment,Male,Medication Initiation,762.779941,Susceptible
72958,70_to_74,2100,187,United States of America,BBBM Testing and Treatment,Male,Medication Initiation,574.782529,Susceptible
72959,75_to_79,2100,187,United States of America,BBBM Testing and Treatment,Male,Medication Initiation,556.363648,Susceptible

In [101]:
treatments_prepped.query("measure=='Medication Initiation'").disease_stage.unique()

['Preclinical AD', 'Susceptible']
Categories (2, object): ['Preclinical AD', 'Susceptible']

In [102]:
treatments_prepped.query("disease_stage=='Susceptible'").scenario.unique()

['BBBM Testing and Treatment']
Categories (2, object): ['BBBM Testing and Treatment', 'bbbm_testing_and_treatment']

In [103]:
treatments_prepped.query("scenario in ['BBBM Testing Only', 'bbbm_testing']").value.unique()

array([], dtype=float64)

In [ ]:
with Timer():
    treatments_output = results.summarize_and_beautify(treatments_prepped, 'disease_stage')

print(len(treatments_output), 'rows')
treatments_output.head()

Timer SummarizingTimer started
2025-12-05 02:27:03.551905
2025-12-05 02:27:28.269117
2025-12-05 02:34:41.682436
Elapsed time: 458.1447 seconds
Elapsed time: 0:07:38.145301
291840 rows

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,60_to_64,Female,Preclinical AD,Reference,Medication Completion,Number,0.0,0.0,0.0
1,2025,Brazil,60_to_64,Male,Preclinical AD,Reference,Medication Completion,Number,0.0,0.0,0.0
2,2025,Brazil,60_to_64,Both,Preclinical AD,Reference,Medication Completion,Number,0.0,0.0,0.0
3,2025,Brazil,60_to_64,Female,Preclinical AD,BBBM Testing Only,Medication Completion,Number,0.0,0.0,0.0
4,2025,Brazil,60_to_64,Male,Preclinical AD,BBBM Testing Only,Medication Completion,Number,0.0,0.0,0.0

In [ ]:
treatments_output.query(
    "Year == 2100 & Location == 'United States of America' & Age == '75_to_79' & Sex == 'Male' & `Disease Stage` == 'Susceptible' & Scenario == 'BBBM Testing and Treatment' & Measure == 'Medication Initiation'"
)
# orig mean: 93092.973924
# new mean: 41049.447242

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
200632,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,1447.502596,1345.344124,1529.890856
200638,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Rate,0.000222,0.000219,0.000224

In [ ]:
41049.447242 / 93092.973924

0.4409510783865631

In [ ]:
# Save treatments output
treatments_output.to_csv(output_dir / 'medication.csv', index=False)

# Process months of treatment

In [ ]:
treatment_months
# Needed columns:
# year, location, age group, sex, scenario, sub-entity (months of treatment), value (count)

,age_group,artifact_path,entity,entity_type,event_year,input_draw,measure,scenario,sex,sub_entity,value,location
0,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,1,0.0,Japan
1,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,2,0.0,Japan
2,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,3,0.0,Japan
3,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,4,0.0,Japan
4,65_to_69,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2025,35,treatment_duration_count,bbbm_testing_and_treatment,Female,5,0.0,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...
164155,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,5,194.0,China
164156,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,6,188.0,China
164157,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,7,225.0,China
164158,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,8,188.0,China
164159,75_to_79,/mnt/team/simulation_science/pub/models/vivari...,treatment,cause,2100,123,treatment_duration_count,bbbm_testing_and_treatment,Male,9,14545.0,China

In [114]:
treatment_months_prepped = results.process_months_of_treatment(treatment_months)
treatment_months_prepped

,age_group,event_year,input_draw,measure,scenario,sex,months_of_treatment,value,location,metric,disease_stage
0,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,1,0,Japan,Number,Preclinical AD
1,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,2,0,Japan,Number,Preclinical AD
2,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,3,0,Japan,Number,Preclinical AD
3,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,4,0,Japan,Number,Preclinical AD
4,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,5,0,Japan,Number,Preclinical AD
...,...,...,...,...,...,...,...,...,...,...,...
164155,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,5,194,China,Number,Preclinical AD
164156,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,6,188,China,Number,Preclinical AD
164157,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,7,225,China,Number,Preclinical AD
164158,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,8,188,China,Number,Preclinical AD
164159,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,9,14545,China,Number,Preclinical AD

In [113]:
treatment_months_prepped.astype({'value': 'int'})

,age_group,event_year,input_draw,measure,scenario,sex,months_of_treatment,value,location,metric,disease_stage
0,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,1,0,Japan,Number,Preclinical AD
1,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,2,0,Japan,Number,Preclinical AD
2,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,3,0,Japan,Number,Preclinical AD
3,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,4,0,Japan,Number,Preclinical AD
4,65_to_69,2025,35,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,5,0,Japan,Number,Preclinical AD
...,...,...,...,...,...,...,...,...,...,...,...
164155,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,5,194,China,Number,Preclinical AD
164156,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,6,188,China,Number,Preclinical AD
164157,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,7,225,China,Number,Preclinical AD
164158,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,8,188,China,Number,Preclinical AD
164159,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,9,14545,China,Number,Preclinical AD

In [109]:
treatment_months_prepped.pivot(
    columns='input_draw',
    index=treatment_months_prepped.columns.difference(['input_draw', 'value']).tolist(),
    values='value',
    )

input_draw                                                                                                                                                             35  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
65_to_69  Preclinical AD 2025       Brazil                   Treatments by number of doses completed Number 1                   bbbm_testing_and_treatment Female     0.0
                                                                                                                                                           Male       0.0
                                                                                                            2                   bbbm_testing_and_treatment Female     0.0
                                                                                                                                                           Male       0.0
                                                                                                            3                   bbbm_testing_and_treatment Female     0.0
...                                                                                                                                                                   ...
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 7                   bbbm_testing_and_treatment Male      83.0
                                                                                                            8                   bbbm_testing_and_treatment Female   109.0
                                                                                                                                                           Male      57.0
                                                                                                            9                   bbbm_testing_and_treatment Female  7451.0
                                                                                                                                                           Male    5805.0

input_draw                                                                                                                                                             41  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
65_to_69  Preclinical AD 2025       Brazil                   Treatments by number of doses completed Number 1                   bbbm_testing_and_treatment Female     0.0
                                                                                                                                                           Male       0.0
                                                                                                            2                   bbbm_testing_and_treatment Female     0.0
                                                                                                                                                           Male       0.0
                                                                                                            3                   bbbm_testing_and_treatment Female     0.0
...                                                                                                                                                                   ...
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 7                   bbbm_testing_and_treatment Male      64.0
                                                                                                            8                   bbbm_testing_and_treatment Female   120.0
                                                                                                                                                           Male      77.0
                                                                                                            9                   bbbm_testing_and_treatment Female  7519.0
                                                                                                                                                           Male    4220.0

input_draw                                                                                                                                                            123  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
65_to_69  Preclinical AD 2025       Brazil                   Treatments by number of doses completed Number 1                   bbbm_testing_and_treatment Female     0.0
                                                                                                                                                           Male       0.0
                                                                                                            2                   bbbm_testing_and_treatment Female     0.0
                                                                                                                                                           Male       0.0
                                                                                                            3                   bbbm_testing_and_treatment Female     0.0
...                                                                                                                                                                   ...
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 7                   bbbm_testing_and_treatment Male     124.0
                                                                                                            8                   bbbm_testing_and_treatment Female   123.0
                                                                                                                                                           Male      96.0
                                                                                                            9                   bbbm_testing_and_treatment Female  8031.0
                                                                                                                                                           Male    8268.0

input_draw                                                                                                                                                            187
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
65_to_69  Preclinical AD 2025       Brazil                   Treatments by number of doses completed Number 1                   bbbm_testing_and_treatment Female     0.0
                                                                                                                                                           Male       0.0
                                                                                                            2                   bbbm_testing_and_treatment Female     0.0
                                                                                                                                                           Male       0.0
                                                                                                            3                   bbbm_testing_and_treatment Female     0.0
...                                                                                                                                                                   ...
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 7                   bbbm_testing_and_treatment Male     104.0
                                                                                                            8                   bbbm_testing_and_treatment Female   115.0
                                                                                                                                                           Male     114.0
                                                                                                            9                   bbbm_testing_and_treatment Female  8277.0
                                                                                                                                                           Male    7838.0

[41040 rows x 4 columns]

In [117]:
df = results.ops.pivot_draws(treatment_months_prepped)
df

                                                                                                                                                                   draw_35  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
65_to_69  Preclinical AD 2025       Brazil                   Treatments by number of doses completed Number 1                   bbbm_testing_and_treatment Female        0
                                                                                                                                                           Male          0
                                                                                                            2                   bbbm_testing_and_treatment Female        0
                                                                                                                                                           Male          0
                                                                                                            3                   bbbm_testing_and_treatment Female        0
...                                                                                                                                                                    ...
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 7                   bbbm_testing_and_treatment Male         83
                                                                                                            8                   bbbm_testing_and_treatment Female      109
                                                                                                                                                           Male         57
                                                                                                            9                   bbbm_testing_and_treatment Female     7451
                                                                                                                                                           Male       5805

                                                                                                                                                                   draw_41  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
65_to_69  Preclinical AD 2025       Brazil                   Treatments by number of doses completed Number 1                   bbbm_testing_and_treatment Female        0
                                                                                                                                                           Male          0
                                                                                                            2                   bbbm_testing_and_treatment Female        0
                                                                                                                                                           Male          0
                                                                                                            3                   bbbm_testing_and_treatment Female        0
...                                                                                                                                                                    ...
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 7                   bbbm_testing_and_treatment Male         64
                                                                                                            8                   bbbm_testing_and_treatment Female      120
                                                                                                                                                           Male         77
                                                                                                            9                   bbbm_testing_and_treatment Female     7519
                                                                                                                                                           Male       4220

                                                                                                                                                                   draw_123  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
65_to_69  Preclinical AD 2025       Brazil                   Treatments by number of doses completed Number 1                   bbbm_testing_and_treatment Female         0
                                                                                                                                                           Male           0
                                                                                                            2                   bbbm_testing_and_treatment Female         0
                                                                                                                                                           Male           0
                                                                                                            3                   bbbm_testing_and_treatment Female         0
...                                                                                                                                                                     ...
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 7                   bbbm_testing_and_treatment Male         124
                                                                                                            8                   bbbm_testing_and_treatment Female       123
                                                                                                                                                           Male          96
                                                                                                            9                   bbbm_testing_and_treatment Female      8031
                                                                                                                                                           Male        8268

                                                                                                                                                                   draw_187
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
65_to_69  Preclinical AD 2025       Brazil                   Treatments by number of doses completed Number 1                   bbbm_testing_and_treatment Female         0
                                                                                                                                                           Male           0
                                                                                                            2                   bbbm_testing_and_treatment Female         0
                                                                                                                                                           Male           0
                                                                                                            3                   bbbm_testing_and_treatment Female         0
...                                                                                                                                                                     ...
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 7                   bbbm_testing_and_treatment Male         104
                                                                                                            8                   bbbm_testing_and_treatment Female       115
                                                                                                                                                           Male         114
                                                                                                            9                   bbbm_testing_and_treatment Female      8277
                                                                                                                                                           Male        7838

[41040 rows x 4 columns]

In [125]:
temp = vh.utils.mean_lower_upper(df.iloc[-15:], axis=1).join(df)
temp

                                                                                                                                                                      mean  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 2                   bbbm_testing_and_treatment Male      91.50
                                                                                                            3                   bbbm_testing_and_treatment Female   106.00
                                                                                                                                                           Male      88.00
                                                                                                            4                   bbbm_testing_and_treatment Female   117.25
                                                                                                                                                           Male      90.00
                                                                                                            5                   bbbm_testing_and_treatment Female   113.75
                                                                                                                                                           Male      98.25
                                                                                                            6                   bbbm_testing_and_treatment Female   109.75
                                                                                                                                                           Male      85.25
                                                                                                            7                   bbbm_testing_and_treatment Female   108.25
                                                                                                                                                           Male      93.75
                                                                                                            8                   bbbm_testing_and_treatment Female   116.75
                                                                                                                                                           Male      86.00
                                                                                                            9                   bbbm_testing_and_treatment Female  7819.50
                                                                                                                                                           Male    6532.75

                                                                                                                                                                      lower  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 2                   bbbm_testing_and_treatment Male      63.400
                                                                                                            3                   bbbm_testing_and_treatment Female    96.450
                                                                                                                                                           Male      76.225
                                                                                                            4                   bbbm_testing_and_treatment Female   110.075
                                                                                                                                                           Male      59.125
                                                                                                            5                   bbbm_testing_and_treatment Female    95.375
                                                                                                                                                           Male      68.025
                                                                                                            6                   bbbm_testing_and_treatment Female   102.225
                                                                                                                                                           Male      54.200
                                                                                                            7                   bbbm_testing_and_treatment Female   106.150
                                                                                                                                                           Male      65.425
                                                                                                            8                   bbbm_testing_and_treatment Female   109.450
                                                                                                                                                           Male      58.500
                                                                                                            9                   bbbm_testing_and_treatment Female  7456.100
                                                                                                                                                           Male    4338.875

                                                                                                                                                                      upper  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 2                   bbbm_testing_and_treatment Male     115.350
                                                                                                            3                   bbbm_testing_and_treatment Female   120.650
                                                                                                                                                           Male     113.375
                                                                                                            4                   bbbm_testing_and_treatment Female   129.100
                                                                                                                                                           Male     116.625
                                                                                                            5                   bbbm_testing_and_treatment Female   132.550
                                                                                                                                                           Male     124.650
                                                                                                            6                   bbbm_testing_and_treatment Female   118.550
                                                                                                                                                           Male     109.925
                                                                                                            7                   bbbm_testing_and_treatment Female   110.775
                                                                                                                                                           Male     122.500
                                                                                                            8                   bbbm_testing_and_treatment Female   122.775
                                                                                                                                                           Male     112.650
                                                                                                            9                   bbbm_testing_and_treatment Female  8258.550
                                                                                                                                                           Male    8235.750

                                                                                                                                                                   draw_35  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 2                   bbbm_testing_and_treatment Male         95
                                                                                                            3                   bbbm_testing_and_treatment Female       96
                                                                                                                                                           Male         79
                                                                                                            4                   bbbm_testing_and_treatment Female      118
                                                                                                                                                           Male         73
                                                                                                            5                   bbbm_testing_and_treatment Female      100
                                                                                                                                                           Male         93
                                                                                                            6                   bbbm_testing_and_treatment Female      113
                                                                                                                                                           Male         69
                                                                                                            7                   bbbm_testing_and_treatment Female      108
                                                                                                                                                           Male         83
                                                                                                            8                   bbbm_testing_and_treatment Female      109
                                                                                                                                                           Male         57
                                                                                                            9                   bbbm_testing_and_treatment Female     7451
                                                                                                                                                           Male       5805

                                                                                                                                                                   draw_41  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 2                   bbbm_testing_and_treatment Male         61
                                                                                                            3                   bbbm_testing_and_treatment Female      102
                                                                                                                                                           Male         76
                                                                                                            4                   bbbm_testing_and_treatment Female      130
                                                                                                                                                           Male         58
                                                                                                            5                   bbbm_testing_and_treatment Female       95
                                                                                                                                                           Male         66
                                                                                                            6                   bbbm_testing_and_treatment Female      102
                                                                                                                                                           Male         53
                                                                                                            7                   bbbm_testing_and_treatment Female      106
                                                                                                                                                           Male         64
                                                                                                            8                   bbbm_testing_and_treatment Female      120
                                                                                                                                                           Male         77
                                                                                                            9                   bbbm_testing_and_treatment Female     7519
                                                                                                                                                           Male       4220

                                                                                                                                                                   draw_123  \
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 2                   bbbm_testing_and_treatment Male          93
                                                                                                            3                   bbbm_testing_and_treatment Female       122
                                                                                                                                                           Male         116
                                                                                                            4                   bbbm_testing_and_treatment Female       110
                                                                                                                                                           Male         112
                                                                                                            5                   bbbm_testing_and_treatment Female       127
                                                                                                                                                           Male         108
                                                                                                            6                   bbbm_testing_and_treatment Female       105
                                                                                                                                                           Male         110
                                                                                                            7                   bbbm_testing_and_treatment Female       108
                                                                                                                                                           Male         124
                                                                                                            8                   bbbm_testing_and_treatment Female       123
                                                                                                                                                           Male          96
                                                                                                            9                   bbbm_testing_and_treatment Female      8031
                                                                                                                                                           Male        8268

                                                                                                                                                                   draw_187
age_group disease_stage  event_year location                 measure                                 metric months_of_treatment scenario                   sex
75_to_79  Preclinical AD 2100       United States of America Treatments by number of doses completed Number 2                   bbbm_testing_and_treatment Male         117
                                                                                                            3                   bbbm_testing_and_treatment Female       104
                                                                                                                                                           Male          81
                                                                                                            4                   bbbm_testing_and_treatment Female       111
                                                                                                                                                           Male         117
                                                                                                            5                   bbbm_testing_and_treatment Female       133
                                                                                                                                                           Male         126
                                                                                                            6                   bbbm_testing_and_treatment Female       119
                                                                                                                                                           Male         109
                                                                                                            7                   bbbm_testing_and_treatment Female       111
                                                                                                                                                           Male         104
                                                                                                            8                   bbbm_testing_and_treatment Female       115

In [127]:
treatment_months_prepped.iloc[-15:]

,age_group,event_year,input_draw,measure,scenario,sex,months_of_treatment,value,location,metric,disease_stage
164145,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,4,182,China,Number,Preclinical AD
164146,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,5,195,China,Number,Preclinical AD
164147,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,6,173,China,Number,Preclinical AD
164148,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,7,212,China,Number,Preclinical AD
164149,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,8,211,China,Number,Preclinical AD
164150,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Female,9,13734,China,Number,Preclinical AD
164151,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,1,182,China,Number,Preclinical AD
164152,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,2,164,China,Number,Preclinical AD
164153,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,3,210,China,Number,Preclinical AD
164154,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,4,200,China,Number,Preclinical AD
164155,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,5,194,China,Number,Preclinical AD
164156,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,6,188,China,Number,Preclinical AD
164157,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,7,225,China,Number,Preclinical AD
164158,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,8,188,China,Number,Preclinical AD
164159,75_to_79,2100,123,Treatments by number of doses completed,bbbm_testing_and_treatment,Male,9,14545,China,Number,Preclinical AD

In [131]:
temp = treatment_months_prepped.iloc[-15:]
results.scale_up_and_append_rates_and_aggregates(temp)

,input_draw,location,age_group,disease_stage,event_year,measure,metric,months_of_treatment,scenario,sex,value
0,123,China,75_to_79,Preclinical AD,2100,Treatments by number of doses completed,Number,4,bbbm_testing_and_treatment,Female,2697.938984
1,123,China,75_to_79,Preclinical AD,2100,Treatments by number of doses completed,Number,5,bbbm_testing_and_treatment,Female,2890.648911
2,123,China,75_to_79,Preclinical AD,2100,Treatments by number of doses completed,Number,6,bbbm_testing_and_treatment,Female,2564.524419
3,123,China,75_to_79,Preclinical AD,2100,Treatments by number of doses completed,Number,7,bbbm_testing_and_treatment,Female,3142.654201
4,123,China,75_to_79,Preclinical AD,2100,Treatments by number of doses completed,Number,8,bbbm_testing_and_treatment,Female,3127.830360
...,...,...,...,...,...,...,...,...,...,...,...
18325,187,United Kingdom,75_to_79,NaN,2100,NaN,Rate,NaN,NaN,Female,NaN
18326,187,United Kingdom,75_to_79,NaN,2100,NaN,Rate,NaN,NaN,Male,NaN
18327,187,United States of America,75_to_79,NaN,2100,NaN,Rate,NaN,NaN,Both,NaN
18328,187,United States of America,75_to_79,NaN,2100,NaN,Rate,NaN,NaN,Female,NaN
18329,187,United States of America,75_to_79,NaN,2100,NaN,Rate,NaN,NaN,Male,NaN

In [126]:
results.do_final_processing(treatment_months_prepped.iloc[-15:], include_draws=True)

2026-02-20 18:01:07.451313
Timer SummarizingTimer started
Elapsed time: 32.0047 seconds
2026-02-20 18:01:39.646634

,Year,Location,Age,Sex,Disease Stage,Scenario,Months of Treatment,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_plus,Both,NaN,NaN,NaN,NaN,Rate,NaN,NaN,NaN
1,2025,Brazil,65_plus,Female,NaN,NaN,NaN,NaN,Rate,NaN,NaN,NaN
2,2025,Brazil,65_plus,Male,NaN,NaN,NaN,NaN,Rate,NaN,NaN,NaN
3,2025,China,65_plus,Both,NaN,NaN,NaN,NaN,Rate,NaN,NaN,NaN
4,2025,China,65_plus,Female,NaN,NaN,NaN,NaN,Rate,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4651,2100,China,75_to_79,Female,Preclinical AD,BBBM Testing and Treatment,8.0,Treatments by number of doses completed,Rate,0.000065,0.000065,0.000065
4652,2100,China,75_to_79,Male,Preclinical AD,BBBM Testing and Treatment,8.0,Treatments by number of doses completed,Rate,0.000063,0.000063,0.000063
4653,2100,China,75_to_79,Both,Preclinical AD,BBBM Testing and Treatment,9.0,Treatments by number of doses completed,Rate,0.004530,0.004530,0.004530
4654,2100,China,75_to_79,Female,Preclinical AD,BBBM Testing and Treatment,9.0,Treatments by number of doses completed,Rate,0.004206,0.004206,0.004206
4655,2100,China,75_to_79,Male,Preclinical AD,BBBM Testing and Treatment,9.0,Treatments by number of doses completed,Rate,0.004885,0.004885,0.004885

NameError: name 'results' is not defined

# Check some stuff

In [ ]:
!ls -halt $output_dir

total 524M
-rw-rw-r-- 1 ndbs       Domain Users  35M Dec  5 02:34 medication.csv
-rw-rw-r-- 1 ndbs       Domain Users  91M Dec  5 02:25 csf_pet_tests.csv
-rw-rw-r-- 1 ndbs       Domain Users  30M Dec  5 02:05 bbbm_tests.csv
drwxrwxr-x 2 ndbs       Domain Users    0 Dec  5 01:17 version3
drwxrwxr-x 5 ndbs       Domain Users    2 Dec  5 01:17 .
drwxrwxrwx 7 2074479877    310492440    0 Dec  4 13:19 ..
-rw-rw-r-- 1 ndbs       Domain Users  83M Nov 24 22:12 incidence.csv
-rw-rw-r-- 1 ndbs       Domain Users  84M Nov 24 22:02 prevalence.csv
-rw-rw-r-- 1 ndbs       Domain Users 140M Nov 24 21:37 dalys.csv
-rw-rw-r-- 1 ndbs       Domain Users  48M Nov 24 21:15 deaths.csv
drwxrwxr-x 2 ndbs       Domain Users    0 Nov 24 20:19 version2
drwxrwxr-x 2 ndbs       Domain Users    0 Nov 17 11:53 version1

In [ ]:
treatments_output

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,60_to_64,Female,Preclinical AD,Reference,Medication Completion,Number,0.000000,0.000000,0.000000
1,2025,Brazil,60_to_64,Male,Preclinical AD,Reference,Medication Completion,Number,0.000000,0.000000,0.000000
2,2025,Brazil,60_to_64,Both,Preclinical AD,Reference,Medication Completion,Number,0.000000,0.000000,0.000000
3,2025,Brazil,60_to_64,Female,Preclinical AD,BBBM Testing Only,Medication Completion,Number,0.000000,0.000000,0.000000
4,2025,Brazil,60_to_64,Male,Preclinical AD,BBBM Testing Only,Medication Completion,Number,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
291835,2100,United States of America,60_plus,Male,Susceptible,BBBM Testing Only,Medication Initiation,Rate,0.000000,0.000000,0.000000
291836,2100,United States of America,60_plus,Both,Susceptible,BBBM Testing Only,Medication Initiation,Rate,0.000000,0.000000,0.000000
291837,2100,United States of America,60_plus,Female,Susceptible,BBBM Testing and Treatment,Medication Initiation,Rate,0.000102,0.000100,0.000103
291838,2100,United States of America,60_plus,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Rate,0.000112,0.000111,0.000113
291839,2100,United States of America,60_plus,Both,Susceptible,BBBM Testing and Treatment,Medication Initiation,Rate,0.000106,0.000105,0.000107

In [ ]:
treatments_output.query("`Disease Stage` == 'Preclinical AD'").Year.unique()

[2025, 2026, 2027, 2028, 2029, ..., 2096, 2097, 2098, 2099, 2100]
Length: 76
Categories (76, int64): [2025, 2026, 2027, 2028, ..., 2097, 2098, 2099, 2100]

In [ ]:
treatments_prepped.age_group.unique()

['60_to_64', '65_to_69', '70_to_74', '75_to_79', '80_to_84']
Categories (5, object): ['60_to_64', '65_to_69', '70_to_74', '75_to_79', '80_to_84']

In [ ]:
treatment_rates = results.calculate_rate(treatments_prepped)
treatment_rates

,age_group,event_year,input_draw,location,sex,disease_stage,measure,scenario,value,metric
0,60_to_64,2025,2,Brazil,Both,NaN,NaN,NaN,NaN,Rate
1,60_to_64,2025,2,Brazil,Female,Preclinical AD,Medication Completion,baseline,0.000000,Rate
2,60_to_64,2025,2,Brazil,Female,Preclinical AD,Medication Discontinuation,baseline,0.000000,Rate
3,60_to_64,2025,2,Brazil,Female,Preclinical AD,Medication Completion,bbbm_testing,0.000000,Rate
4,60_to_64,2025,2,Brazil,Female,Preclinical AD,Medication Discontinuation,bbbm_testing,0.000000,Rate
...,...,...,...,...,...,...,...,...,...,...
2678995,80_to_84,2100,499,United States of America,Male,Preclinical AD,Medication Initiation,baseline,0.000000,Rate
2678996,80_to_84,2100,499,United States of America,Male,Preclinical AD,Medication Initiation,bbbm_testing,0.000000,Rate
2678997,80_to_84,2100,499,United States of America,Male,Preclinical AD,Medication Initiation,bbbm_testing,0.000000,Rate
2678998,80_to_84,2100,499,United States of America,Male,Preclinical AD,Medication Initiation,bbbm_testing_and_treatment,0.000073,Rate
2678999,80_to_84,2100,499,United States of America,Male,Preclinical AD,Medication Initiation,bbbm_testing_and_treatment,0.000011,Rate

In [ ]:
treatment_rates.query("disease_stage=='Susceptible'")

,age_group,event_year,input_draw,location,sex,disease_stage,measure,scenario,value,metric
13,60_to_64,2025,2,Brazil,Female,Susceptible,Medication Initiation,BBBM Testing Only,0.000000,Rate
14,60_to_64,2025,2,Brazil,Female,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000000,Rate
27,60_to_64,2025,2,Brazil,Male,Susceptible,Medication Initiation,BBBM Testing Only,0.000000,Rate
28,60_to_64,2025,2,Brazil,Male,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000000,Rate
42,60_to_64,2025,2,China,Female,Susceptible,Medication Initiation,BBBM Testing Only,0.000000,Rate
...,...,...,...,...,...,...,...,...,...,...
2203970,75_to_79,2100,499,United Kingdom,Male,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000893,Rate
2203984,75_to_79,2100,499,United States of America,Female,Susceptible,Medication Initiation,BBBM Testing Only,0.000000,Rate
2203985,75_to_79,2100,499,United States of America,Female,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000089,Rate
2203998,75_to_79,2100,499,United States of America,Male,Susceptible,Medication Initiation,BBBM Testing Only,0.000000,Rate
2203999,75_to_79,2100,499,United States of America,Male,Susceptible,Medication Initiation,BBBM Testing and Treatment,0.000099,Rate

In [ ]:
mslt_results_prepped.query("measure.str.contains('Medication')")

,input_draw,location,age_group,disease_stage,event_year,measure,metric,scenario,sex,value
1216,2,Brazil,60_to_64,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Female,0.000000
1217,2,Brazil,65_to_69,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Female,0.000000
1218,2,Brazil,70_to_74,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Female,0.000000
1219,2,Brazil,75_to_79,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Female,0.000000
1220,2,Brazil,60_to_64,Susceptible,2025,Medication Initiation,Number,BBBM Testing Only,Male,0.000000
...,...,...,...,...,...,...,...,...,...,...
911995,499,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,677.239164
911996,499,United States of America,60_to_64,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,640.926233
911997,499,United States of America,65_to_69,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,638.365092
911998,499,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,318.225318
911999,499,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,634.542556

In [ ]:
mslt_results_prepped.measure.unique()

['BBBM Tests', 'Positive BBBM Tests', 'Medication Initiation']
Categories (3, object): ['BBBM Tests', 'Medication Initiation', 'Positive BBBM Tests']

# Scratchwork

In [ ]:
bbbm_tests_prepped

,age_group,event_year,input_draw,location,measure,scenario,sex,value,disease_stage,metric
0,60_to_64,2025,2,Japan,BBBM Tests,baseline,Female,0.000000,Preclinical AD,Number
1,60_to_64,2025,2,Japan,BBBM Tests,baseline,Male,0.000000,Preclinical AD,Number
2,60_to_64,2025,2,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
3,60_to_64,2025,2,Japan,BBBM Tests,bbbm_testing,Male,0.000000,Preclinical AD,Number
4,60_to_64,2025,2,Japan,BBBM Tests,bbbm_testing_and_treatment,Female,0.000000,Preclinical AD,Number
...,...,...,...,...,...,...,...,...,...,...
1519995,75_to_79,2100,499,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Female,2257.463881,Susceptible,Number
1519996,60_to_64,2100,499,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,2136.420776,Susceptible,Number
1519997,65_to_69,2100,499,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,2127.883639,Susceptible,Number
1519998,70_to_74,2100,499,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,1060.751059,Susceptible,Number
1519999,75_to_79,2100,499,United States of America,Positive BBBM Tests,BBBM Testing and Treatment,Male,2115.141854,Susceptible,Number

In [ ]:
column_name_map = {
            'event_year': 'Year',
            'age_group': 'Age',
            'location': 'Location',
            'sex': 'Sex',
            'scenario': 'Scenario',
            'measure': 'Measure',
            'metric': 'Metric',
            'disease_stage': 'Disease Stage',
            'input_draw': 'Draw',
            'value': 'Value',
            'mean': 'Mean',
            'lower': '95% UI Lower',
            'upper': '95% UI Upper',
        }
reverse_map = {v: k for k, v in column_name_map.items()}
reverse_map

{'Year': 'event_year',
 'Age': 'age_group',
 'Location': 'location',
 'Sex': 'sex',
 'Scenario': 'scenario',
 'Measure': 'measure',
 'Metric': 'metric',
 'Disease Stage': 'disease_stage',
 'Draw': 'input_draw',
 'Value': 'value',
 'Mean': 'mean',
 '95% UI Lower': 'lower',
 '95% UI Upper': 'upper'}

In [ ]:
temp = mslt_results.rename(columns=reverse_map)
temp

,event_year,location,age_group,sex,disease_stage,scenario,measure,metric,input_draw,value
0,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_113,0.000000
1,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_13,0.000000
2,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_158,0.000000
3,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_169,0.000000
4,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_177,0.000000
...,...,...,...,...,...,...,...,...,...,...
151995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_46,1449.331177
151996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_460,1470.158543
151997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_480,1382.121956
151998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_499,1425.476623
151999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Improper Medication Uses,Number,draw_89,1523.571603

In [ ]:
pd.concat([bbbm_tests_prepped, temp])

,age_group,event_year,input_draw,location,measure,scenario,sex,value,disease_stage,metric
0,60_to_64,2025,2,Japan,BBBM Tests,baseline,Female,0.000000,Preclinical AD,Number
1,60_to_64,2025,2,Japan,BBBM Tests,baseline,Male,0.000000,Preclinical AD,Number
2,60_to_64,2025,2,Japan,BBBM Tests,bbbm_testing,Female,0.000000,Preclinical AD,Number
3,60_to_64,2025,2,Japan,BBBM Tests,bbbm_testing,Male,0.000000,Preclinical AD,Number
4,60_to_64,2025,2,Japan,BBBM Tests,bbbm_testing_and_treatment,Female,0.000000,Preclinical AD,Number
...,...,...,...,...,...,...,...,...,...,...
151995,75_to_79,2100,draw_46,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,1449.331177,Susceptible,Number
151996,75_to_79,2100,draw_460,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,1470.158543,Susceptible,Number
151997,75_to_79,2100,draw_480,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,1382.121956,Susceptible,Number
151998,75_to_79,2100,draw_499,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,1425.476623,Susceptible,Number
151999,75_to_79,2100,draw_89,United States of America,Improper Medication Uses,BBBM Testing and Treatment,Male,1523.571603,Susceptible,Number

In [ ]:
temp.query("measure.str.contains('Medication') and value > 0 and scenario=='BBBM Testing Only'")

,event_year,location,age_group,sex,disease_stage,scenario,measure,metric,input_draw,value
1000,2030,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_113,482.306322
1001,2030,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_13,508.659351
1002,2030,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_158,496.935839
1003,2030,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_169,480.363688
1004,2030,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_177,435.431225
...,...,...,...,...,...,...,...,...,...,...
151995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_46,1449.331177
151996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_460,1470.158543
151997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_480,1382.121956
151998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_499,1425.476623
151999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing Only,Improper Medication Uses,Number,draw_89,1523.571603

In [ ]:
temp.measure.unique()

array(['BBBM Tests', 'BBBM False Positive Tests',
       'Improper Medication Uses'], dtype=object)

In [ ]:
temp.replace(
    {'measure': {'BBBM False Positive Tests': 'BBBM Positive Tests',
 'Improper Medication Uses': 'Medication Initiation'}})

,event_year,location,age_group,sex,disease_stage,scenario,measure,metric,input_draw,value
0,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_113,0.000000
1,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_13,0.000000
2,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_158,0.000000
3,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_169,0.000000
4,2025,Brazil,60_to_64,Female,Susceptible,BBBM Testing Only,BBBM Tests,Number,draw_177,0.000000
...,...,...,...,...,...,...,...,...,...,...
151995,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_46,1449.331177
151996,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_460,1470.158543
151997,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_480,1382.121956
151998,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_499,1425.476623
151999,2100,United States of America,75_to_79,Male,Susceptible,BBBM Testing and Treatment,Medication Initiation,Number,draw_89,1523.571603

In [ ]:
bbbm_tests_prepped.dtypes

age_group        category
event_year       category
input_draw       category
location         category
measure          category
scenario         category
sex              category
value             float64
disease_stage    category
metric           category
dtype: object

In [ ]:
testing = temp.query("scenario=='BBBM Testing Only'").drop(columns='scenario')
treatment = temp.query("scenario=='BBBM Testing and Treatment'").drop(columns='scenario')
# This shows that the whole dataframe was copied to the testing-only
# scenario, including medication initiations, which is incorrect
results.ops.compare_values(testing, treatment)

Empty DataFrame
Columns: []
Index: []

In [ ]:
mslt_results_processed = results.process_mslt_results(mslt_results)
mslt_results_processed

,input_draw,location,age_group,disease_stage,event_year,measure,metric,scenario,sex,value
0,2,Brazil,60_to_64,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
1,2,Brazil,65_to_69,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
2,2,Brazil,70_to_74,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
3,2,Brazil,75_to_79,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Female,0.000000
4,2,Brazil,60_to_64,Susceptible,2025,BBBM Tests,Number,BBBM Testing Only,Male,0.000000
...,...,...,...,...,...,...,...,...,...,...
911995,499,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Female,677.239164
911996,499,United States of America,60_to_64,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,640.926233
911997,499,United States of America,65_to_69,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,638.365092
911998,499,United States of America,70_to_74,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,318.225318
911999,499,United States of America,75_to_79,Susceptible,2100,Medication Initiation,Number,BBBM Testing and Treatment,Male,634.542556

In [ ]:
mslt_results_processed.input_draw.unique()

[2, 13, 24, 41, 46, ..., 446, 457, 460, 480, 499]
Length: 25
Categories (25, int64): [2, 13, 24, 41, ..., 457, 460, 480, 499]

In [ ]:
print_memory_usage(mslt_results_processed)

15.510179 MB

In [ ]:
mslt_results_processed.measure.unique()

['BBBM Tests', 'Positive BBBM Tests', 'Medication Initiation']
Categories (3, object): ['BBBM Tests', 'Medication Initiation', 'Positive BBBM Tests']

In [ ]:
!date

Fri Dec  5 02:35:02 PST 2025