In [ ]:
import pandas as pd
import os
from pathlib import Path

!date
!whoami
!pwd

Fri Mar 13 19:13:12 PDT 2026
ndbs
/mnt/share/code/ndbs/vivarium_research_alzheimers/results_tables

In [ ]:
intermediate_output_dir = Path("/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/final_csvs_in_progress/draws")
final_output_dir = Path("/mnt/team/simulation_science/pub/models/vivarium_csu_alzheimers/results/final_csvs_in_progress/no_draws")

# Find all intermediate CSV files except for medication_doses.csv
with os.scandir(intermediate_output_dir) as entries:
    csv_names = [entry.name for entry in entries
                 if entry.is_file() and entry.name.endswith(".csv")
                 # Exclude medication_doses.csv since we don't want to
                 # give it to client
                 and entry.name != "medication_doses.csv"]

# Loop through each CSV file, read it, drop draw columns, and write to
# final output directory
for filename in csv_names:
    df = pd.read_csv(intermediate_output_dir / filename)
    draw_cols = [col for col in df.columns if col.startswith("draw_")]
    df = df.drop(columns=draw_cols)
    df.to_csv(final_output_dir / filename, index=False)
    # # Verify final output -- doesn't work due to rounding floating
    # # point values to 12 decimal places when writing to CSV
    # temp = pd.read_csv(final_output_dir / filename)
    # assert temp.equals(df), f"Data mismatch in {filename}"

csv_names

['deaths.csv',
 'incidence.csv',
 'dalys.csv',
 'medication.csv',
 'population.csv',
 'prevalence.csv',
 'csf_pet_tests.csv',
 'bbbm_tests.csv',
 'medication_doses.csv']

In [6]:
df

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_to_69,Female,AD Dementia,Reference,Deaths Associated with AD,Number,2682.490014,2019.276367,3272.446759
1,2025,Brazil,65_to_69,Male,AD Dementia,Reference,Deaths Associated with AD,Number,1293.566515,961.454346,1509.876539
2,2025,Brazil,65_to_69,Both,AD Dementia,Reference,Deaths Associated with AD,Number,3976.056529,3106.672560,4666.200936
3,2025,Brazil,65_to_69,Female,AD Dementia,BBBM Testing Only,Deaths Associated with AD,Number,2682.490014,2019.276367,3272.446759
4,2025,Brazil,65_to_69,Male,AD Dementia,BBBM Testing Only,Deaths Associated with AD,Number,1293.566515,961.454346,1509.876539
...,...,...,...,...,...,...,...,...,...,...,...
341995,2100,United States of America,65_plus,Male,AD Dementia,BBBM Testing Only,Averted Deaths Associated with AD,Rate,0.000000,0.000000,0.000000
341996,2100,United States of America,65_plus,Both,AD Dementia,BBBM Testing Only,Averted Deaths Associated with AD,Rate,0.000000,0.000000,0.000000
341997,2100,United States of America,65_plus,Female,AD Dementia,BBBM Testing and Treatment,Averted Deaths Associated with AD,Rate,0.000149,0.000110,0.000193
341998,2100,United States of America,65_plus,Male,AD Dementia,BBBM Testing and Treatment,Averted Deaths Associated with AD,Rate,0.000094,0.000064,0.000126
341999,2100,United States of America,65_plus,Both,AD Dementia,BBBM Testing and Treatment,Averted Deaths Associated with AD,Rate,0.000124,0.000089,0.000157

In [7]:
temp

,Year,Location,Age,Sex,Disease Stage,Scenario,Measure,Metric,Mean,95% UI Lower,95% UI Upper
0,2025,Brazil,65_to_69,Female,AD Dementia,Reference,Deaths Associated with AD,Number,2682.490014,2019.276367,3272.446759
1,2025,Brazil,65_to_69,Male,AD Dementia,Reference,Deaths Associated with AD,Number,1293.566515,961.454346,1509.876539
2,2025,Brazil,65_to_69,Both,AD Dementia,Reference,Deaths Associated with AD,Number,3976.056529,3106.672560,4666.200936
3,2025,Brazil,65_to_69,Female,AD Dementia,BBBM Testing Only,Deaths Associated with AD,Number,2682.490014,2019.276367,3272.446759
4,2025,Brazil,65_to_69,Male,AD Dementia,BBBM Testing Only,Deaths Associated with AD,Number,1293.566515,961.454346,1509.876539
...,...,...,...,...,...,...,...,...,...,...,...
341995,2100,United States of America,65_plus,Male,AD Dementia,BBBM Testing Only,Averted Deaths Associated with AD,Rate,0.000000,0.000000,0.000000
341996,2100,United States of America,65_plus,Both,AD Dementia,BBBM Testing Only,Averted Deaths Associated with AD,Rate,0.000000,0.000000,0.000000
341997,2100,United States of America,65_plus,Female,AD Dementia,BBBM Testing and Treatment,Averted Deaths Associated with AD,Rate,0.000149,0.000110,0.000193
341998,2100,United States of America,65_plus,Male,AD Dementia,BBBM Testing and Treatment,Averted Deaths Associated with AD,Rate,0.000094,0.000064,0.000126
341999,2100,United States of America,65_plus,Both,AD Dementia,BBBM Testing and Treatment,Averted Deaths Associated with AD,Rate,0.000124,0.000089,0.000157

In [8]:
df.compare(temp)

                Mean                 95% UI Lower                 \
                self         other           self          other
0                NaN           NaN    2019.276367    2019.276367
3                NaN           NaN    2019.276367    2019.276367
6                NaN           NaN    2019.276367    2019.276367
207     2.164300e-08  2.164300e-08            NaN            NaN
239              NaN           NaN            NaN            NaN
...              ...           ...            ...            ...
341796           NaN           NaN  216482.580077  216482.580077
341880  2.522622e+05  2.522622e+05            NaN            NaN
341883  2.522622e+05  2.522622e+05            NaN            NaN
341970           NaN           NaN  220510.921332  220510.921332
341973           NaN           NaN  220510.921332  220510.921332

        95% UI Upper
                self         other
0                NaN           NaN
3                NaN           NaN
6                NaN           NaN
207              NaN           NaN
239     2.059034e-07  2.059034e-07
...              ...           ...
341796           NaN           NaN
341880           NaN           NaN
341883           NaN           NaN
341970           NaN           NaN
341973           NaN           NaN

[5758 rows x 6 columns]

In [10]:
df.loc[0, '95% UI Lower'], temp.loc[0, '95% UI Lower']

(2019.2763674402236, 2019.276367440224)

In [1]:
df

NameError: name 'df' is not defined